// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CgPOwaXkGgCRgAtEn1VIGCxEHI-brjg',
    appId: '1:355243461054:web:5533510cdd0a97a29a51ef',
    messagingSenderId: '355243461054',
    projectId: 'temphist-2c787',
    authDomain: 'temphist-2c787.firebaseapp.com',
    storageBucket: 'temphist-2c787.firebasestorage.app',
    measurementId: 'G-LS8NGKDW6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHvBz63WvcYJEFRd890Zpprc223xu0HT4',
    appId: '1:355243461054:android:f3b6a6c685ece8779a51ef',
    messagingSenderId: '355243461054',
    projectId: 'temphist-2c787',
    storageBucket: 'temphist-2c787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS4VM-12TT5795W1x9uzfdAciNEF0tUJM',
    appId: '1:355243461054:ios:a49282a0b4deaa9e9a51ef',
    messagingSenderId: '355243461054',
    projectId: 'temphist-2c787',
    storageBucket: 'temphist-2c787.firebasestorage.app',
    iosBundleId: 'com.turnpiece.temphist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS4VM-12TT5795W1x9uzfdAciNEF0tUJM',
    appId: '1:355243461054:ios:a49282a0b4deaa9e9a51ef',
    messagingSenderId: '355243461054',
    projectId: 'temphist-2c787',
    storageBucket: 'temphist-2c787.firebasestorage.app',
    iosBundleId: 'com.turnpiece.temphist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8CgPOwaXkGgCRgAtEn1VIGCxEHI-brjg',
    appId: '1:355243461054:web:ee20ee5c77358e3f9a51ef',
    messagingSenderId: '355243461054',
    projectId: 'temphist-2c787',
    authDomain: 'temphist-2c787.firebaseapp.com',
    storageBucket: 'temphist-2c787.firebasestorage.app',
    measurementId: 'G-LDZDNBY0F9',
  );

}