import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:timezone/data/latest.dart' as tz_data;
import 'package:geolocator/geolocator.dart' as geo;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is auto-generated by FlutterFire CLI
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

import 'package:flutter/services.dart';
import 'dart:io' as io;
import 'dart:async'; // Added for StreamSubscription and StreamController
import 'dart:convert'; // Added for jsonEncode/jsonDecode

import 'models/selection_method.dart';
import 'services/analytics_service.dart';
import 'services/auth_service.dart';
import 'services/temperature_service.dart';
import 'services/share_service.dart';
import 'services/location_service.dart';
import 'services/period_cache_service.dart';
import 'utils/debug_utils.dart';
import 'widgets/period_page.dart';
import 'widgets/splash_screen.dart';
import 'widgets/onboarding/onboarding_screen.dart';
import 'widgets/location_selector_sheet.dart';
import 'widgets/settings_sheet.dart';
import 'services/temperature_unit_service.dart';
import 'utils/temperature_utils.dart';
import 'constants/app_constants.dart';
import 'utils/date_utils.dart' as date_utils;
import 'services/location_selection_service.dart';

// Delegate to shared utility functions
Map<String, String> _getCurrentDateAndLocation(
  String determinedLocation, {
  String? locationTimezone,
}) =>
    date_utils.getCurrentDateAndLocation(
      determinedLocation,
      locationTimezone: locationTimezone,
    );

/// Check available storage space and return true if sufficient space is available
Future<bool> _checkStorageSpace() async {
  try {
    if (io.Platform.isAndroid || io.Platform.isIOS) {
      // For mobile platforms, we can't easily check storage space
      // but we can try to write a small test file to see if storage is available
      final tempDir = io.Directory.systemTemp;
      final testFile = io.File('${tempDir.path}/temp_storage_test.tmp');

      try {
        await testFile.writeAsString('test');
        // Write succeeded — storage is available.
        // Delete is best-effort; ignore errors (the OS may have already removed
        // the file, e.g. on the iOS simulator).
        try {
          await testFile.delete();
        } catch (_) {}
        return true;
      } catch (e) {
        DebugUtils.logLazy(() => 'Storage test failed: $e');
        return false;
      }
    } else {
      // For desktop platforms, check available disk space
      final tempDir = io.Directory.systemTemp;
      await tempDir
          .stat(); // Basic check - if we can access temp dir, assume space is available
      return true;
    }
  } catch (e) {
    DebugUtils.logLazy(() => 'Storage space check failed: $e');
    return false;
  }
}

/// Safely execute SharedPreferences operations with storage space checks
Future<T?> _safeSharedPreferencesOperation<T>(
  Future<T> Function() operation,
  String operationName,
) async {
  try {
    // Check storage space before attempting operation
    final hasSpace = await _checkStorageSpace();
    if (!hasSpace) {
      DebugUtils.logLazy(
          () => '⚠️ Insufficient storage space for $operationName');
      return null;
    }

    return await operation();
  } catch (e) {
    DebugUtils.logLazy(() => '❌ SharedPreferences $operationName failed: $e');

    // If it's a storage-related error, try to clear some cache
    if (e.toString().contains('No space left') ||
        e.toString().contains('ENOSPC') ||
        e.toString().contains('storage')) {
      DebugUtils.logLazy(
          () => '🧹 Storage error detected, attempting cache cleanup');
      await _emergencyCacheCleanup();

      // Try the operation once more after cleanup
      try {
        return await operation();
      } catch (e2) {
        DebugUtils.logLazy(() => '❌ Operation still failed after cleanup: $e2');
        return null;
      }
    }

    return null;
  }
}

/// Emergency cache cleanup when storage is full
Future<void> _emergencyCacheCleanup() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    final keys = prefs.getKeys();
    int cleanedCount = 0;

    // Remove oldest cache entries first (those with oldest timestamps)
    final cacheEntries = <String, int>{};

    for (final key in keys) {
      if (key.startsWith('tempData_') ||
          key.startsWith('api_') ||
          key.startsWith('cachedLocation')) {
        try {
          final data = prefs.getString(key);
          if (data != null) {
            final json = jsonDecode(data) as Map<String, dynamic>;
            final timestamp = json['timestamp'];
            if (timestamp is int) {
              cacheEntries[key] = timestamp;
            }
          }
        } catch (e) {
          // If we can't parse the data, remove it immediately
          await prefs.remove(key);
          cleanedCount++;
        }
      }
    }

    // Sort by timestamp (oldest first) and remove oldest 50% of entries
    final sortedEntries = cacheEntries.entries.toList()
      ..sort((a, b) => a.value.compareTo(b.value));

    final entriesToRemove = (sortedEntries.length * 0.5).ceil();
    for (int i = 0; i < entriesToRemove && i < sortedEntries.length; i++) {
      await prefs.remove(sortedEntries[i].key);
      cleanedCount++;
    }

    DebugUtils.logLazy(
        () => '🧹 Emergency cleanup removed $cleanedCount cache entries');
  } catch (e) {
    DebugUtils.logLazy(() => '❌ Emergency cache cleanup failed: $e');
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock phones to portrait; tablets use system default (all orientations).
  // On iOS the Info.plist ~ipad key already declares landscape for iPads.
  final isTablet = WidgetsBinding.instance.platformDispatcher.views.first
              .physicalSize.shortestSide /
          WidgetsBinding
              .instance.platformDispatcher.views.first.devicePixelRatio >=
      600;
  await SystemChrome.setPreferredOrientations(
    isTablet
        ? [] // let the system / Info.plist decide for tablets
        : [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );

  // Configure system UI overlay to extend app background over status bar and navigation bar
  _setSystemUIOverlayStyle();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAppCheck.instance.activate(
    providerAndroid: kDebugMode ? const AndroidDebugProvider() : const AndroidPlayIntegrityProvider(),
    providerApple: kDebugMode ? const AppleDebugProvider() : const AppleDeviceCheckProvider(),
  );
  // Ensure user is signed in (anonymous)
  await _ensureSignedIn();
  await PeriodCacheService.init();
  tz_data.initializeTimeZones();
  runApp(TempHist());
}

void _setSystemUIOverlayStyle() {
  if (io.Platform.isIOS) {
    // iOS-specific configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark, // Light text on dark background
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    );
  } else if (io.Platform.isAndroid) {
    // Android-specific configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light, // Light icons/text
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    );
  } else {
    // For other platforms, use a default configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: Colors.transparent,
      ),
    );
  }
}

Future<void> _ensureSignedIn() async {
  if (FirebaseAuth.instance.currentUser == null) {
    await AuthService.signInAnonymously(maxRetries: 3, rethrowOnFailure: false);
  }
}

class TempHist extends StatelessWidget {
  const TempHist({super.key});

  @override
  Widget build(BuildContext context) {
    // Ensure system UI overlay is set correctly
    _setSystemUIOverlayStyle();

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: kAppTitle,
      home: const TemperatureScreen(),
      // Cap Dynamic Type — beyond the limit chart labels, location header, and
      // settings sheet overflow. iPads have more room so allow a higher cap.
      builder: (context, child) {
        final isIpad = MediaQuery.of(context).size.shortestSide >=
            kTabletBreakpointWidth;
        return MediaQuery.withClampedTextScaling(
          maxScaleFactor: isIpad ? 1.6 : 1.3,
          child: child!,
        );
      },
      // Add a custom loading screen theme
      theme: ThemeData(
        scaffoldBackgroundColor: kBackgroundColour,
        // This helps prevent the white flash during initialization
        colorScheme: ColorScheme.fromSeed(
          seedColor: kAccentColour,
          brightness: Brightness.dark,
        ),
      ),
    );
  }
}

class TemperatureScreen extends StatefulWidget {
  final Future<Map<String, dynamic>?>? testFuture;

  const TemperatureScreen({super.key, this.testFuture});

  @override
  TemperatureScreenState createState() => TemperatureScreenState();
}

class TemperatureScreenState extends State<TemperatureScreen>
    with WidgetsBindingObserver {
  // Temperature unit preference (°C / °F).
  final TemperatureUnitService _unitService = TemperatureUnitService();
  bool get _isFahrenheit => _unitService.isFahrenheit.value;

  // Location is managed by the LocationService; these getters provide
  // backward-compatible access throughout the class.
  final LocationService _locationService = LocationService();
  String get _determinedLocation => _locationService.determinedLocation;
  String get _displayLocation => _locationService.displayLocation;
  bool get _isLocationDetermined => _locationService.isLocationDetermined;

  // Track app initialization state
  bool _isAppInitialized = false;
  bool _splashScreenMinTimeElapsed = false;
  Timer? _splashScreenTimer;
  final Completer<void> _splashCompleter = Completer<void>();

  // Guards auto-opening of the location selector on first launch with no GPS.
  bool _onboardingCheckComplete = false;
  bool _locationSelectorAutoOpened = false;

  geo.Position? get _lastPosition => _locationService.lastPosition;

  // Incremented whenever the location/unit changes so in-flight prefetch
  // polls for the old configuration can detect they are stale and bail out.
  int _prefetchGeneration = 0;

  // Tracks the date identifier (MM-DD) of the last data load so we can
  // detect midnight rollovers and reload all period pages.
  String _lastDateIdentifier = '';

  // Network connectivity state
  bool _isOnline = true;
  StreamSubscription<List<ConnectivityResult>>? _connectivitySubscription;

  // Memory management
  int _memoryCleanupCount = 0;

  // Carries the selection method from the most recent user-initiated location
  // pick into _prefetchPeriodData so it can be included in the analytics event.
  // Cleared after being consumed by the first prefetch call.
  SelectionMethod? _pendingSelectionMethod;

  // Page view for period switching (daily / weekly / monthly / yearly)
  late final PageController _pageController;
  final ValueNotifier<int> _pageIndexNotifier = ValueNotifier<int>(0);

  // Trend slope (°C/decade) per page index, populated as each period loads.
  final _periodSlopes = <int, double?>{};

  // Tracks the active page's vertical scroll offset so the period nav can
  // collapse as the user scrolls (and re-expand when they scroll back up).
  final ValueNotifier<double> _activeScrollOffsetNotifier =
      ValueNotifier<double>(0.0);

  // Combined height of the period segmented control plus its bottom padding —
  // i.e. how far the user must scroll to fully collapse the nav.
  static const double _kPeriodTabsCollapseHeight = 58.0;

  static const List<String> _periodKeys = ['daily', 'week', 'month', 'year'];
  bool _isSharing = false;
  late final ScrollController _dailyScrollController;
  late final ScrollController _weekScrollController;
  late final ScrollController _monthScrollController;
  late final ScrollController _yearScrollController;
  final _dailyPageKey = GlobalKey<PeriodPageState>();
  final _weekPageKey = GlobalKey<PeriodPageState>();
  final _monthPageKey = GlobalKey<PeriodPageState>();
  final _yearPageKey = GlobalKey<PeriodPageState>();

  // Onboarding
  bool _hasSeenOnboarding =
      true; // default true to avoid flash during async check

  /// Resets scroll positions on all period pages to the top and clears the
  /// collapsed-header state. Call whenever the content is about to reload.
  void _resetScrollPositions() {
    for (final c in [
      _dailyScrollController,
      _weekScrollController,
      _monthScrollController,
      _yearScrollController,
    ]) {
      if (c.hasClients) c.jumpTo(0);
    }
    _activeScrollOffsetNotifier.value = 0.0;
  }

  /// Called whenever [_locationService] notifies listeners.
  void _onLocationChanged() {
    _periodSlopes.clear();
    _resetScrollPositions();
    if (mounted) setState(() {});
  }

  void _onUnitChanged() {
    // The API returns different data (especially summaries) depending on the
    // unit.  Clear the in-memory cache so stale data is not served.
    // PeriodPage widgets detect the isFahrenheit prop change via
    // didUpdateWidget and re-fetch automatically.
    TemperatureService.clearCache();
    _resetScrollPositions();
    if (mounted) {
      _prefetchGeneration++;
      setState(() {});
      _prefetchPeriodData();
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _pageController = PageController();
    _dailyScrollController = ScrollController();
    _weekScrollController = ScrollController();
    _monthScrollController = ScrollController();
    _yearScrollController = ScrollController();

    // Load temperature unit preference (°C / °F) and rebuild on change.
    _unitService.load();
    _unitService.isFahrenheit.addListener(_onUnitChanged);

    // Listen to location changes to trigger UI rebuilds
    _locationService.addListener(_onLocationChanged);
    _locationService.onSignificantLocationChange = _refreshLocationAndData;

    // Start network connectivity monitoring (async: initial check before listen)
    unawaited(_startConnectivityMonitoring());

    // Start minimum splash screen timer
    _startSplashScreenTimer();

    // If we have a test future, skip async initialization — PeriodPage
    // handles its own data loading when a location is set.
    if (widget.testFuture != null) {
      return;
    }

    // Initialize with location determination; PeriodPage widgets self-load
    // once a non-empty location is passed to them.
    _initializeApp();

    // Check whether to show the one-time onboarding flow
    _checkOnboarding();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _pageController.dispose();
    _unitService.isFahrenheit.removeListener(_onUnitChanged);
    _locationService.removeListener(_onLocationChanged);
    _locationService.dispose();
    _connectivitySubscription?.cancel();
    _connectivitySubscription = null;
    _splashScreenTimer?.cancel();
    _splashScreenTimer = null;
    _pageIndexNotifier.dispose();
    _activeScrollOffsetNotifier.dispose();
    _dailyScrollController.dispose();
    _weekScrollController.dispose();
    _monthScrollController.dispose();
    _yearScrollController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    if (state == AppLifecycleState.resumed) {
      DebugUtils.logLazy(
          () => 'App resumed - checking if location or date needs refresh');
      _checkAndRefreshLocationIfNeeded();
      _checkAndRefreshDataIfDateChanged();
      // Silently refresh today's temperature on the daily page if stale.
      unawaited(_dailyPageKey.currentState?.checkAndRefreshTodayIfStale() ??
          Future.value());
      // Cleanup expired cache on resume
      _performMemoryCleanup();
    } else if (state == AppLifecycleState.paused) {
      DebugUtils.logLazy(() => 'App paused - performing memory cleanup');
      _performAggressiveMemoryCleanup();
    } else if (state == AppLifecycleState.detached) {
      DebugUtils.logLazy(() => 'App detached - performing final cleanup');
      _performAggressiveMemoryCleanup();
    }
  }

  Future<void> _initializeApp() async {
    if (widget.testFuture != null) {
      setState(() => _isAppInitialized = true);
      return;
    }

    DebugUtils.verboseLazy(() => 'Initializing app');

    await _cleanupExpiredCache();
    await _determineLocation();

    // Record the current date so we can detect midnight rollovers.
    _lastDateIdentifier = _currentDateIdentifier();

    if (_splashScreenMinTimeElapsed) {
      _onAppInitialized();
    } else {
      _waitForSplashScreenAndInitialize();
    }

    // PeriodPage widgets self-load once _determinedLocation becomes non-empty
    // (via didUpdateWidget). Pre-warm caches for the other periods in the
    // background.
    _prefetchPeriodData();

    _startListeningToLocationChanges();

    DebugUtils.verboseLazy(
        () => 'App initialization completed - location: $_determinedLocation');
  }

  Future<void> _checkAndRefreshLocationIfNeeded() async {
    if (_locationService.isLocationStale()) {
      await _refreshLocationAndData();
    }
  }

  /// Check if the calendar date has rolled over since last load and reload
  /// all period pages if so (e.g. after midnight when the app is resumed).
  void _checkAndRefreshDataIfDateChanged() {
    if (_lastDateIdentifier.isEmpty) return;
    final current = _currentDateIdentifier();
    if (current != _lastDateIdentifier) {
      DebugUtils.logLazy(() =>
          'Date changed ($_lastDateIdentifier → $current), reloading all periods');
      _lastDateIdentifier = current;
      _reloadAllPeriodPages();
    } else {
      DebugUtils.logLazy(
          () => 'Date unchanged ($current), keeping current data');
    }
  }

  /// Computes the MM-DD identifier used for API calls, accounting for the
  /// "use yesterday" threshold.
  String _currentDateIdentifier() {
    final now = DateTime.now();
    final useYesterday = now.hour < kUseYesterdayHourThreshold;
    final dateToUse =
        useYesterday ? now.subtract(const Duration(days: 1)) : now;
    return dateIdentifier(dateToUse);
  }

  /// Force-reload every PeriodPage via its GlobalKey.
  void _reloadAllPeriodPages() {
    for (final key in [
      _dailyPageKey,
      _weekPageKey,
      _monthPageKey,
      _yearPageKey
    ]) {
      key.currentState?.reload();
    }
  }

  Future<void> _refreshLocationAndData() async {
    DebugUtils.logLazy(() => 'Refreshing location and data...');

    final previousLocation = _determinedLocation;

    // Mark refreshing but keep location string so period pages don't flash empty
    _locationService.markRefreshing();

    // Determine new location — PeriodPage widgets will auto-reload via
    // didUpdateWidget when the location prop changes.
    await _determineLocation();

    DebugUtils.logLazy(
        () => 'Location refresh: $previousLocation → $_determinedLocation');
    _prefetchPeriodData();
  }

  // Cache expiration constants
  static const Duration _currentDateCacheExpiration = Duration(hours: 1);
  static const Duration _historicalDataCacheExpiration = Duration(hours: 24);
  static const Duration _summaryCacheExpiration = Duration(hours: 1);
  static const Duration _averageTrendCacheExpiration = Duration(hours: 6);

  /// Clean up expired cache entries
  Future<void> _cleanupExpiredCache() async {
    await _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      final keys = prefs.getKeys();
      final now = DateTime.now();
      int cleanedCount = 0;

      for (final key in keys) {
        if (key.startsWith('tempData_') || key.startsWith('api_')) {
          try {
            final cachedData = prefs.getString(key);
            if (cachedData != null) {
              final data = jsonDecode(cachedData) as Map<String, dynamic>;
              final timestamp =
                  DateTime.fromMillisecondsSinceEpoch(data['timestamp'] as int);
              final age = now.difference(timestamp);

              Duration expiration;
              if (key.startsWith('tempData_')) {
                // Temperature data cache
                final year = data['year'] as int;
                final isCurrentYear = year == now.year;
                expiration = isCurrentYear
                    ? _currentDateCacheExpiration
                    : _historicalDataCacheExpiration;
              } else if (key.startsWith('api_')) {
                // API response cache
                final endpoint = data['endpoint'] as String;
                switch (endpoint) {
                  case 'summary':
                    expiration = _summaryCacheExpiration;
                    break;
                  case 'average':
                  case 'trend':
                    expiration = _averageTrendCacheExpiration;
                    break;
                  default:
                    expiration = const Duration(hours: 1);
                }
              } else {
                continue; // Skip unknown cache types
              }

              if (age > expiration) {
                await prefs.remove(key);
                cleanedCount++;
              }
            }
          } catch (e) {
            // If we can't parse the data, remove it
            await prefs.remove(key);
            cleanedCount++;
          }
        }
      }

      if (cleanedCount > 0) {
        DebugUtils.logLazy(
            () => '🧹 Cleaned up $cleanedCount expired cache entries');
      }
    }, 'cleanup expired cache');
  }

  /// Check whether the onboarding flow should be shown (first launch only).
  Future<void> _checkOnboarding() async {
    if (kDebugMode) {
      await _safeSharedPreferencesOperation(() async {
        final prefs = await SharedPreferences.getInstance();
        await prefs.remove('has_seen_onboarding');
      }, 'reset onboarding flag');
    }

    final seen = await _safeSharedPreferencesOperation<bool>(() async {
      final prefs = await SharedPreferences.getInstance();
      return prefs.getBool('has_seen_onboarding') ?? false;
    }, 'load onboarding flag');

    if (seen == true) {
      if (mounted) {
        _onboardingCheckComplete = true;
        _maybeAutoOpenLocationSelector();
      }
      return;
    }

    if (mounted) {
      setState(() => _hasSeenOnboarding = false);
      _onboardingCheckComplete = true;
      // _hasSeenOnboarding is false here so _maybeAutoOpenLocationSelector will
      // not open the selector now; _completeOnboarding will call it instead.
    }
  }

  /// Mark onboarding as complete and return to the main screen.
  Future<void> _completeOnboarding() async {
    await _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('has_seen_onboarding', true);
    }, 'save onboarding flag');

    if (mounted) {
      setState(() => _hasSeenOnboarding = true);
      // If the app had no location when it started, open the selector now
      // that the user has finished onboarding.
      _maybeAutoOpenLocationSelector();
    }
  }

  Future<void> _determineLocation() async {
    await _locationService.determineLocation();
    // Record GPS auto-detect to API and local history when the device resolved
    // a real position.
    if (_locationService.locationSource == LocationSource.gps &&
        _locationService.determinedLocation.isNotEmpty) {
      _recordLocationSelection(_locationService.determinedLocation);
      _pendingSelectionMethod = SelectionMethod.ownLocation;
    }
  }

  /// Submit a location selection to the API and record it locally.
  ///
  /// Called for all explicit location choices — GPS auto-detect, manual search
  /// picks, popular taps, and visited taps. Never called for background or
  /// programmatic loads.
  void _recordLocationSelection(String apiLocation) {
    unawaited(TemperatureService().submitLocationSelection(apiLocation));
    unawaited(LocationSelectionService.record(apiLocation));
  }

  /// Pre-warm the in-memory and Hive caches for all four periods in parallel.
  /// PeriodPage widgets that have already loaded will hit the in-memory cache
  /// instead of making a duplicate network call.
  ///
  /// When [_pendingSelectionMethod] is set it is consumed here and an analytics
  /// event is fired after the daily period fetch completes.
  Future<void> _prefetchPeriodData() async {
    if (!_isLocationDetermined || _determinedLocation.isEmpty) return;

    // Consume the pending selection method before any await so it is not
    // accidentally re-used by a concurrent call.
    final selectionMethod = _pendingSelectionMethod;
    _pendingSelectionMethod = null;

    final dateInfo = _getCurrentDateAndLocation(
      _determinedLocation,
      locationTimezone: TemperatureService.timezoneFor(_determinedLocation),
    );
    final identifier = dateInfo['mmdd']!;
    final location = _determinedLocation;
    final service = TemperatureService();
    const periods = ['daily', 'week', 'month', 'year'];

    final generation = _prefetchGeneration;
    bool isCancelled() => _prefetchGeneration != generation;

    final isAtGps = _locationService.isAtGpsCity(location);
    final lat = isAtGps ? _lastPosition?.latitude : null;
    final lon = isAtGps ? _lastPosition?.longitude : null;

    DebugUtils.logLazy(() =>
        'Prefetching period data in parallel for $location ($identifier)');

    await Future.wait(
      periods.map((period) async {
        if (isCancelled()) return;
        try {
          DebugUtils.logLazy(() => 'Prefetching $period data');
          final unitGroup = _isFahrenheit ? 'fahrenheit' : null;
          final data = await service.fetchPeriodData(
            period,
            location,
            identifier,
            unitGroup: unitGroup,
            isCancelled: isCancelled,
            onFetchComplete: (period == 'daily' && selectionMethod != null)
                ? (ms, cacheHit) => _fireAnalytics(
                      location: location,
                      selectionMethod: selectionMethod,
                      responseTimeMs: ms,
                      cacheHit: cacheHit,
                    )
                : null,
          );
          if (!isCancelled() && lat != null && lon != null) {
            await PeriodCacheService.put(period, lat, lon, identifier, data,
                unitGroup: unitGroup);
          }
        } catch (e) {
          DebugUtils.logLazy(() => 'Prefetch $period failed: $e');
        }
      }),
    );
  }

  void _fireAnalytics({
    required String location,
    required SelectionMethod selectionMethod,
    required int responseTimeMs,
    bool? cacheHit,
  }) {
    final canonicalId = TemperatureService.canonicalIdFor(location);
    unawaited(AnalyticsService.submit(
      requestedLocation: location,
      canonicalLocation: canonicalId,
      selectionMethod: selectionMethod,
      responseTimeMs: responseTimeMs,
      cacheHit: cacheHit,
    ));
  }

  void _startSplashScreenTimer() {
    // Skip splash screen timer in test mode
    if (widget.testFuture != null) {
      _splashScreenMinTimeElapsed = true;
      if (!_splashCompleter.isCompleted) _splashCompleter.complete();
      return;
    }

    // Show splash screen for minimum 2 seconds to prevent white flash
    _splashScreenTimer = Timer(const Duration(seconds: 2), () {
      if (mounted) {
        setState(() {
          _splashScreenMinTimeElapsed = true;
        });
        if (!_splashCompleter.isCompleted) _splashCompleter.complete();
      }
    });
  }

  Future<void> _waitForSplashScreenAndInitialize() async {
    // Skip in test mode
    if (widget.testFuture != null) {
      setState(() {
        _isAppInitialized = true;
      });
      return;
    }

    await _splashCompleter.future;
    if (mounted) {
      _onAppInitialized();
    }
  }

  /// Sets [_isAppInitialized] then checks whether the location selector should
  /// be auto-opened (deferred until we also know the onboarding state).
  void _onAppInitialized() {
    setState(() {
      _isAppInitialized = true;
    });
    _maybeAutoOpenLocationSelector();
  }

  /// Opens the location selector automatically when:
  ///  - the app is fully initialised,
  ///  - we know whether onboarding is needed (race-condition guard),
  ///  - onboarding has already been seen (so we don't open over it), AND
  ///  - GPS produced no result and there is no saved location history.
  ///
  /// When onboarding *has not* been seen, [_completeOnboarding] will call this
  /// once the user finishes, at which point all conditions will be satisfied.
  void _maybeAutoOpenLocationSelector() {
    if (_locationSelectorAutoOpened) return;
    if (!_isAppInitialized) return;
    if (!_onboardingCheckComplete) return;
    if (!_hasSeenOnboarding) return;
    if (!_locationService.locationPermissionDenied) return;

    _locationSelectorAutoOpened = true;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) _showRequiredLocationSelector();
    });
  }

  /// Opens the settings sheet.
  void _showSettings() {
    SettingsSheet.show(
      context,
      isFahrenheit: _isFahrenheit,
      onUnitChanged: (value) => _unitService.setFahrenheit(value),
      onOpenLocationSelector: _showLocationSelector,
    );
  }

  /// Opens the location selector bottom sheet.
  void _showLocationSelector() {
    LocationSelectorSheet.show(
      context,
      gpsLocation: _locationService.gpsLocation,
      selectedLocation: _determinedLocation,
      onLocationSelected: _onLocationSelected,
      connectivityOnline: _isOnline,
    );
  }

  /// Opens the location selector without a close button, used on first launch
  /// when no location has been determined, so the user must pick a city.
  void _showRequiredLocationSelector() {
    LocationSelectorSheet.show(
      context,
      gpsLocation: _locationService.gpsLocation,
      selectedLocation: _determinedLocation,
      onLocationSelected: _onLocationSelected,
      canDismiss: false,
      connectivityOnline: _isOnline,
    );
  }

  /// Called when the user picks a location from the selector sheet.
  Future<void> _onLocationSelected(
      String apiLocation, SelectionMethod selectionMethod) async {
    if (apiLocation == _determinedLocation) return;

    // Submit selection signal to API and record locally for all explicit picks.
    DebugUtils.logLazy(() => '_onLocationSelected: recording "$apiLocation"');
    _recordLocationSelection(apiLocation);

    final currentPage = _pageIndexNotifier.value;
    final currentPeriod = _periodKeys[currentPage];
    DebugUtils.logLazy(
        () => '📍 Location switch: $_determinedLocation → $apiLocation '
            '(on $currentPeriod page, gps: ${_locationService.gpsLocation})');

    // Purge the in-memory service cache so stale data for the old location
    // is never served to the new fetch.
    TemperatureService.clearCache();
    _prefetchGeneration++;
    _pendingSelectionMethod = selectionMethod;

    await _locationService.setManualLocation(apiLocation);

    // PeriodPage widgets detect the location prop change via didUpdateWidget
    // and re-fetch automatically.  Pre-warm caches for other periods.
    if (!mounted) return;
    _prefetchPeriodData();
  }

  BoxDecoration _trendGradientFor(double? gradientFactor) {
    final f = gradientFactor ?? 0.0;
    final double t = f.abs().clamp(0.0, 1.0);
    final Color top, bottom;
    if (f > 0) {
      top = Color.lerp(kBackgroundColour, kBackgroundWarmColour, t)!;
      bottom = Color.lerp(kBackgroundColourDark, kBackgroundCoolColour, t)!;
    } else if (f < 0) {
      top = Color.lerp(kBackgroundColour, kBackgroundCoolColour, t)!;
      bottom = Color.lerp(kBackgroundColourDark, kBackgroundWarmColour, t)!;
    } else {
      top = kBackgroundColour;
      bottom = kBackgroundColourDark;
    }
    return BoxDecoration(
      gradient: LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [top, bottom],
      ),
    );
  }

  void _onTrendLoaded(int pageIndex, double gradientFactor) {
    DebugUtils.logLazy(() => 'Trend gradient: page $pageIndex factor=$gradientFactor');
    setState(() {
      _periodSlopes[pageIndex] = gradientFactor;
    });
  }

  Widget _buildGradientBackground() {
    return ValueListenableBuilder<int>(
      valueListenable: _pageIndexNotifier,
      builder: (_, pageIndex, __) {
        return SizedBox.expand(
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 800),
            curve: Curves.easeInOut,
            decoration: _trendGradientFor(_periodSlopes[pageIndex]),
          ),
        );
      },
    );
  }

  /// Top-level layout: fixed header (title + debug) and swipeable PageView below.
  Widget _buildPageLayout(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final screenWidth = MediaQuery.of(context).size.width;
        final isTablet = screenWidth >= kTabletBreakpointWidth;
        final maxContentWidth =
            isTablet ? kTabletMaxContentWidth : constraints.maxWidth;
        final contentWidth = constraints.maxWidth > maxContentWidth
            ? maxContentWidth
            : constraints.maxWidth;
        final horizontalMargin =
            isTablet ? (constraints.maxWidth - contentWidth) / 2 : 0.0;

        final sidePad = _standardHorizontalPadding();
        return SizedBox(
          width: constraints.maxWidth,
          child: Center(
            child: Container(
              width: contentWidth,
              margin: EdgeInsets.symmetric(horizontal: horizontalMargin),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildPageHeader(context),
                  ValueListenableBuilder<double>(
                    valueListenable: _activeScrollOffsetNotifier,
                    builder: (_, offset, child) {
                      final t = (offset / _kPeriodTabsCollapseHeight)
                          .clamp(0.0, 1.0);
                      return ClipRect(
                        child: SizedBox(
                          height: _kPeriodTabsCollapseHeight * (1 - t),
                          child: Opacity(
                            opacity: 1 - t,
                            child: OverflowBox(
                              minHeight: _kPeriodTabsCollapseHeight,
                              maxHeight: _kPeriodTabsCollapseHeight,
                              alignment: Alignment.topCenter,
                              child: child,
                            ),
                          ),
                        ),
                      );
                    },
                    child: Padding(
                      padding: EdgeInsets.only(
                        left: sidePad,
                        right: sidePad,
                        bottom: kTitleRowBottomPadding,
                      ),
                      child: ValueListenableBuilder<int>(
                        valueListenable: _pageIndexNotifier,
                        builder: (_, pageIndex, __) =>
                            _buildPeriodTabs(pageIndex),
                      ),
                    ),
                  ),
                  Expanded(
                    child: NotificationListener<ScrollNotification>(
                      onNotification: (n) {
                        if (n.metrics.axis == Axis.vertical) {
                          _activeScrollOffsetNotifier.value = n.metrics.pixels;
                        }
                        return false;
                      },
                      child: PageView(
                        controller: _pageController,
                        onPageChanged: (index) {
                          HapticFeedback.selectionClick();
                          _pageIndexNotifier.value = index;
                          // Sync the period-nav collapse state to the new
                          // active page's scroll position, otherwise the nav
                          // would keep the previous page's collapse state.
                          final controllers = [
                            _dailyScrollController,
                            _weekScrollController,
                            _monthScrollController,
                            _yearScrollController,
                          ];
                          final c = controllers[index];
                          _activeScrollOffsetNotifier.value =
                              c.hasClients ? c.offset : 0.0;
                        },
                        children: [
                          // Page 0: Daily
                          _buildPeriodPage(
                            context,
                            pageIndex: 0,
                            pageKey: _dailyPageKey,
                            periodKey: 'daily',
                            periodLabel: 'daily',
                            scrollController: _dailyScrollController,
                          ),
                          // Page 1: Weekly
                          _buildPeriodPage(
                            context,
                            pageIndex: 1,
                            pageKey: _weekPageKey,
                            periodKey: 'week',
                            periodLabel: 'Past week',
                            scrollController: _weekScrollController,
                          ),
                          // Page 2: Monthly
                          _buildPeriodPage(
                            context,
                            pageIndex: 2,
                            pageKey: _monthPageKey,
                            periodKey: 'month',
                            periodLabel: 'Past month',
                            scrollController: _monthScrollController,
                          ),
                          // Page 3: Yearly
                          _buildPeriodPage(
                            context,
                            pageIndex: 3,
                            pageKey: _yearPageKey,
                            periodKey: 'year',
                            periodLabel: 'Past year',
                            scrollController: _yearScrollController,
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildPageHeader(BuildContext context) {
    return ValueListenableBuilder<int>(
      valueListenable: _pageIndexNotifier,
      builder: (context, pageIndex, _) {
        final locationColour = _locationColour;
        final headerText = _displayLocation.isNotEmpty
            ? _displayLocation
            : (_determinedLocation.isNotEmpty
                ? _determinedLocation
                : 'Loading location...');
        final headerCc = TemperatureService.countryCodeFor(_determinedLocation);
        final headerFlag =
            headerCc != null ? TemperatureService.flagEmoji(headerCc) : null;

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Location row: flag + city name + share + settings
            Padding(
              padding: EdgeInsets.only(
                top: 14,
                bottom: 8,
                left: kScreenPadding + kContentHorizontalMargin,
                right: kScreenPadding + kContentHorizontalMargin,
              ),
              child: Row(
                children: [
                  Expanded(
                    child: Semantics(
                      label: _isLocationDetermined
                          ? 'Change location. Currently: $headerText'
                          : headerText,
                      button: _isLocationDetermined,
                      child: GestureDetector(
                        onTap: _isLocationDetermined
                            ? _showLocationSelector
                            : null,
                        behavior: HitTestBehavior.opaque,
                        child: Row(
                          children: [
                            if (headerFlag != null)
                              Text(
                                headerFlag,
                                style: const TextStyle(fontSize: kIconSize + 6),
                              )
                            else
                              Icon(
                                Icons.location_on_outlined,
                                color: locationColour.withValues(alpha: 0.8),
                                size: kIconSize + 6,
                              ),
                            const SizedBox(width: 6),
                            Expanded(
                              child: Text(
                                headerText,
                                style: TextStyle(
                                  color: locationColour,
                                  fontSize: kFontSizeLocation,
                                  fontWeight: FontWeight.w600,
                                  letterSpacing: 0.5,
                                ),
                                overflow: TextOverflow.ellipsis,
                                maxLines: 1,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  // Share icon
                  GestureDetector(
                    onTap: _isSharing
                        ? null
                        : () => _shareCurrentPeriod(pageIndex),
                    behavior: HitTestBehavior.opaque,
                    child: Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 10, vertical: 8),
                      child: _isSharing
                          ? SizedBox(
                              width: kIconSize + 6,
                              height: kIconSize + 6,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: kGreyLabelColour.withValues(alpha: 0.7),
                              ),
                            )
                          : Icon(
                              Icons.ios_share,
                              color: kGreyLabelColour.withValues(alpha: 0.7),
                              size: kIconSize + 6,
                            ),
                    ),
                  ),
                  // Settings gear
                  Semantics(
                    label: 'Open settings',
                    button: true,
                    child: GestureDetector(
                      onTap: _showSettings,
                      behavior: HitTestBehavior.opaque,
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 10, vertical: 8),
                        child: Icon(
                          Icons.settings,
                          color: kGreyLabelColour.withValues(alpha: 0.7),
                          size: kIconSize + 8,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        );
      },
    );
  }

  Future<void> _shareCurrentPeriod(int pageIndex) async {
    final periodKey = switch (pageIndex) {
      0 => 'daily',
      1 => 'week',
      2 => 'month',
      3 => 'year',
      _ => null,
    };
    if (periodKey == null) return;

    setState(() => _isSharing = true);
    try {
      final dateInfo = _getCurrentDateAndLocation(
        _determinedLocation,
        locationTimezone: TemperatureService.timezoneFor(_determinedLocation),
      );
      final dateToUse = DateTime.parse(dateInfo['date']!);
      final identifier = dateIdentifier(dateToUse);
      final refYear = dateToUse.year;
      final unit = _isFahrenheit ? 'fahrenheit' : 'celsius';

      final shareService = ShareService();

      final shareUrl = await shareService.createShare(
        location: _determinedLocation,
        period: periodKey,
        identifier: identifier,
        refYear: refYear,
        unit: unit,
      );

      // Clear the spinner before opening the native sheet. The share future
      // may never resolve on iOS if the user dismisses without selecting an
      // action, which would leave _isSharing stuck as true indefinitely.
      if (mounted) setState(() => _isSharing = false);

      await shareService.share(
        shareUrl: shareUrl,
        shareButtonKey: null,
      );
    } catch (e) {
      DebugUtils.logLazy(() => 'Share failed: $e');
      if (mounted) {
        setState(() => _isSharing = false);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Could not create share link. Please try again.'),
            backgroundColor: kErrorColour,
          ),
        );
      }
    }
  }

  static const List<String> _periodLabels = [
    'Daily',
    'Past week',
    'Past month',
    'Past year'
  ];
  static const List<String> _tabLabels = ['Today', 'Week', 'Month', 'Year'];

  Widget _buildPeriodTabs(int pageIndex) {
    const innerPadding = 2.0;
    const pillRadius = 20.0;

    return Semantics(
      label:
          '${_periodLabels[pageIndex]}. Period ${pageIndex + 1} of ${_periodKeys.length}. Tap or swipe to change.',
      child: ExcludeSemantics(
        child: Container(
          decoration: BoxDecoration(
            color: kSegmentedControlBackgroundColour,
            borderRadius: BorderRadius.circular(pillRadius),
          ),
          padding: const EdgeInsets.all(innerPadding),
          child: Row(
            children: [
              for (int i = 0; i < _tabLabels.length; i++)
                Expanded(
                  child: GestureDetector(
                    onTap: () => _pageController.animateToPage(
                      i,
                      duration: const Duration(milliseconds: 300),
                      curve: Curves.easeInOut,
                    ),
                    behavior: HitTestBehavior.opaque,
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      curve: Curves.easeInOut,
                      decoration: BoxDecoration(
                        color: i == pageIndex
                            ? kSegmentedControlSelectedBackgroundColour
                            : Colors.transparent,
                        borderRadius:
                            BorderRadius.circular(pillRadius - innerPadding),
                      ),
                      padding: const EdgeInsets.symmetric(vertical: 6),
                      alignment: Alignment.center,
                      child: Text(
                        _tabLabels[i],
                        style: TextStyle(
                          color: i == pageIndex
                              ? kSegmentedControlSelectedTextColour
                              : kSegmentedControlUnselectedTextColour,
                          fontSize: kFontSizeBody - 2,
                          fontWeight: i == pageIndex
                              ? FontWeight.w600
                              : FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildLocationAndHeadingContent(int pageIndex) {
    return Text(
      _buildPeriodHeaderLabel(pageIndex),
      style: const TextStyle(
        color: kTextPrimaryColour,
        fontSize: kFontSizeBody,
        fontWeight: FontWeight.w600,
      ),
      overflow: TextOverflow.ellipsis,
    );
  }

  Color get _locationColour {
    if (!_isLocationDetermined) return kGreyLabelColour.withValues(alpha: 0.4);
    switch (_locationService.locationSource) {
      case LocationSource.gps:
        // Green — your actual GPS location, matches the current-year bar.
        return kBarCurrentYearColour;
      case LocationSource.recentlyVisited:
        // Secondary green for places the user has already been.
        return kLocationRecentColour;
      case LocationSource.manual:
        // Neutral silver for searched or popular locations.
        return kLocationPopularColour;
    }
  }

  String _buildPeriodHeaderLabel(int pageIndex) {
    final dateInfo = _getCurrentDateAndLocation(
      _determinedLocation,
      locationTimezone: TemperatureService.timezoneFor(_determinedLocation),
    );
    final dateToUse = DateTime.parse(dateInfo['date']!);
    final displayDate = _formatDayMonth(dateToUse);

    switch (pageIndex) {
      case 0:
        return displayDate;
      case 1:
        return 'Week ending $displayDate';
      case 2:
        return 'Month ending $displayDate';
      case 3:
        return 'Year ending $displayDate';
      default:
        return displayDate;
    }
  }

  /// Builds a period page (daily, weekly, monthly, or yearly).
  Widget _buildPeriodPage(
    BuildContext context, {
    required int pageIndex,
    required GlobalKey<PeriodPageState> pageKey,
    required String periodKey,
    required String periodLabel,
    required ScrollController scrollController,
  }) {
    final isAtGps = _locationService.isAtGpsCity(_determinedLocation);
    final lat = isAtGps ? _lastPosition?.latitude : null;
    final lon = isAtGps ? _lastPosition?.longitude : null;

    final sidePad = _standardHorizontalPadding();
    return RepaintBoundary(
      child: PeriodPage(
        key: pageKey,
        periodKey: periodKey,
        periodLabel: periodLabel,
        location: _determinedLocation,
        displayLocation: _displayLocation.isNotEmpty ? _displayLocation : null,
        latitude: lat,
        longitude: lon,
        locationTimezone: TemperatureService.timezoneFor(_determinedLocation),
        scrollController: scrollController,
        topContent: Padding(
          padding: EdgeInsets.only(
            left: sidePad,
            right: sidePad,
            bottom: kSectionBottomPadding,
          ),
          child: _buildLocationAndHeadingContent(pageIndex),
        ),
        isFahrenheit: _isFahrenheit,
        onTrendLoaded: (slope) => _onTrendLoaded(pageIndex, slope),
      ),
    );
  }

  double _standardHorizontalPadding() =>
      kScreenPadding + kContentHorizontalMargin;

  /// Start monitoring network connectivity: initial check completes before
  /// subscribing so the first [onConnectivityChanged] event does not race ahead
  /// of [checkConnectivity] and overwrite a correct offline state.
  Future<void> _startConnectivityMonitoring() async {
    try {
      final initialResults = await Connectivity().checkConnectivity();
      if (mounted) {
        _isOnline = initialResults.any((result) =>
            result == ConnectivityResult.mobile ||
            result == ConnectivityResult.wifi ||
            result == ConnectivityResult.ethernet);
        DebugUtils.logLazy(() =>
            '🌐 Initial connectivity status: ${_isOnline ? "online" : "offline"}');
        setState(() {});
      }
    } catch (e) {
      DebugUtils.logLazy(() => '⚠️ Failed to check initial connectivity: $e');
      // Default to online if check fails (already set to true by default)
    }

    if (!mounted) return;

    _connectivitySubscription = Connectivity().onConnectivityChanged.listen(
      (List<ConnectivityResult> results) {
        final wasOnline = _isOnline;
        _isOnline = results.any((result) =>
            result == ConnectivityResult.mobile ||
            result == ConnectivityResult.wifi ||
            result == ConnectivityResult.ethernet);

        DebugUtils.logLazy(() =>
            '🌐 Network connectivity changed: ${_isOnline ? "online" : "offline"}');

        // If we just came back online and were offline, try to refresh data
        if (!wasOnline && _isOnline) {
          DebugUtils.logLazy(
              () => '🔄 Network restored, attempting to refresh data');
          _handleNetworkRestored();
        }

        // Update UI to reflect connectivity state (_isOnline was updated above)
        if (mounted) {
          DebugUtils.logLazy(() =>
              '🌐 Updating UI for connectivity state: ${_isOnline ? "online" : "offline"}');
          setState(() {
            // _isOnline was already updated above — this triggers a rebuild.
          });
        }
      },
    );
  }

  Widget _buildOfflineBanner() {
    return Material(
      color: kStatsBubbleColour,
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
        child: Row(
          children: [
            Icon(Icons.wifi_off, color: kErrorColour, size: kIconSize + 2),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                'You appear to be offline. Data may be unavailable until you reconnect.',
                style: TextStyle(
                  color: kTextPrimaryColour.withValues(alpha: 0.95),
                  fontSize: kFontSizeBody - 2,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Handle network restoration — only reload pages that have no data.
  /// Pages with existing data are unaffected; reconnecting alone is not a
  /// reason to discard valid cached content.
  void _handleNetworkRestored() {
    DebugUtils.logLazy(() => '🔄 Network restored, reloading pages without data');
    for (final key in [
      _dailyPageKey,
      _weekPageKey,
      _monthPageKey,
      _yearPageKey,
    ]) {
      if (key.currentState?.hasData == false) {
        key.currentState?.reload();
      }
    }
  }

  /// Perform memory cleanup and data optimization
  /// Called on app lifecycle events (resume/pause/detach) instead of periodic timer
  void _performMemoryCleanup() {
    _memoryCleanupCount++;
    DebugUtils.logLazy(
        () => '🧹 Performing memory cleanup #$_memoryCleanupCount');

    try {
      _cleanupExpiredCache();
      DebugUtils.logLazy(() => '✅ Memory cleanup completed');
    } catch (e) {
      DebugUtils.logLazy(() => '❌ Memory cleanup failed: $e');
    }
  }

  /// Perform aggressive memory cleanup when app goes to background
  void _performAggressiveMemoryCleanup() {
    DebugUtils.logLazy(() => '🧹 Performing aggressive memory cleanup');

    try {
      _cleanupExpiredCache();
      DebugUtils.logLazy(() => '✅ Aggressive memory cleanup completed');
    } catch (e) {
      DebugUtils.logLazy(() => '❌ Aggressive memory cleanup failed: $e');
    }
  }

  void _startListeningToLocationChanges() {
    _locationService.startListeningToLocationChanges(
      isLoadingGuard: () => false,
    );
  }

  @override
  Widget build(BuildContext context) {
    // Show splash screen while app is initializing OR minimum time hasn't elapsed
    // Skip splash screen in test mode
    if (widget.testFuture == null &&
        (!_isAppInitialized || !_splashScreenMinTimeElapsed)) {
      return const SplashScreen();
    }

    if (!_hasSeenOnboarding) {
      return OnboardingScreen(
        onComplete: _completeOnboarding,
        unitService: _unitService,
      );
    }

    Widget appContent = Scaffold(
      body: Stack(
        children: [
          // Gradient background fills the whole screen including system areas
          _buildGradientBackground(),
          // Foreground content with fixed header and swipeable pages
          SafeArea(
            bottom: false,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                if (!_isOnline) _buildOfflineBanner(),
                Expanded(child: _buildPageLayout(context)),
              ],
            ),
          ),
        ],
      ),
    );

    // Wrap with AnnotatedRegion for mobile platforms
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
        // iOS uses statusBarBrightness, Android uses statusBarIconBrightness
        statusBarBrightness: io.Platform.isIOS ? Brightness.dark : null,
        statusBarIconBrightness: io.Platform.isIOS ? null : Brightness.light,
      ),
      child: appContent,
    );
  }
}

String _formatDayMonth(DateTime date) => date_utils.formatDateWithOrdinal(date);
