import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:geolocator/geolocator.dart' as geo;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is auto-generated by FlutterFire CLI
import 'package:firebase_auth/firebase_auth.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

import 'package:flutter/services.dart';
import 'dart:io' as io;
import 'dart:async'; // Added for StreamSubscription and StreamController
import 'dart:convert'; // Added for jsonEncode/jsonDecode

import 'services/auth_service.dart';
import 'services/temperature_service.dart';
import 'services/share_service.dart';
import 'services/location_service.dart';
import 'services/period_cache_service.dart';
import 'config/app_config.dart';
import 'utils/debug_utils.dart';
import 'widgets/period_page.dart';
import 'widgets/splash_screen.dart';
import 'widgets/onboarding/onboarding_screen.dart';
import 'widgets/location_selector_sheet.dart';
import 'widgets/settings_sheet.dart';
import 'services/temperature_unit_service.dart';
import 'utils/temperature_utils.dart';
import 'constants/app_constants.dart';
import 'utils/date_utils.dart' as date_utils;

// Delegate to shared utility functions
Map<String, String> _getCurrentDateAndLocation(String determinedLocation) =>
    date_utils.getCurrentDateAndLocation(determinedLocation);


/// Check available storage space and return true if sufficient space is available
Future<bool> _checkStorageSpace() async {
  try {
    if (io.Platform.isAndroid || io.Platform.isIOS) {
      // For mobile platforms, we can't easily check storage space
      // but we can try to write a small test file to see if storage is available
      final tempDir = io.Directory.systemTemp;
      final testFile = io.File('${tempDir.path}/temp_storage_test.tmp');
      
      try {
        await testFile.writeAsString('test');
        // Write succeeded — storage is available.
        // Delete is best-effort; ignore errors (the OS may have already removed
        // the file, e.g. on the iOS simulator).
        try {
          await testFile.delete();
        } catch (_) {}
        return true;
      } catch (e) {
        DebugUtils.logLazy(() => 'Storage test failed: $e');
        return false;
      }
    } else {
      // For desktop platforms, check available disk space
      final tempDir = io.Directory.systemTemp;
      await tempDir.stat(); // Basic check - if we can access temp dir, assume space is available
      return true;
    }
  } catch (e) {
    DebugUtils.logLazy(() => 'Storage space check failed: $e');
    return false;
  }
}

/// Safely execute SharedPreferences operations with storage space checks
Future<T?> _safeSharedPreferencesOperation<T>(
  Future<T> Function() operation,
  String operationName,
) async {
  try {
    // Check storage space before attempting operation
    final hasSpace = await _checkStorageSpace();
    if (!hasSpace) {
      DebugUtils.logLazy(() => '⚠️ Insufficient storage space for $operationName');
      return null;
    }
    
    return await operation();
  } catch (e) {
    DebugUtils.logLazy(() => '❌ SharedPreferences $operationName failed: $e');
    
    // If it's a storage-related error, try to clear some cache
    if (e.toString().contains('No space left') || 
        e.toString().contains('ENOSPC') ||
        e.toString().contains('storage')) {
      DebugUtils.logLazy(() => '🧹 Storage error detected, attempting cache cleanup');
      await _emergencyCacheCleanup();
      
      // Try the operation once more after cleanup
      try {
        return await operation();
      } catch (e2) {
        DebugUtils.logLazy(() => '❌ Operation still failed after cleanup: $e2');
        return null;
      }
    }
    
    return null;
  }
}

/// Emergency cache cleanup when storage is full
Future<void> _emergencyCacheCleanup() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    final keys = prefs.getKeys();
    int cleanedCount = 0;
    
    // Remove oldest cache entries first (those with oldest timestamps)
    final cacheEntries = <String, int>{};
    
    for (final key in keys) {
      if (key.startsWith('tempData_') || key.startsWith('api_') || key.startsWith('cachedLocation')) {
        try {
          final data = prefs.getString(key);
          if (data != null) {
            final json = jsonDecode(data) as Map<String, dynamic>;
            final timestamp = json['timestamp'];
            if (timestamp is int) {
              cacheEntries[key] = timestamp;
            }
          }
        } catch (e) {
          // If we can't parse the data, remove it immediately
          await prefs.remove(key);
          cleanedCount++;
        }
      }
    }
    
    // Sort by timestamp (oldest first) and remove oldest 50% of entries
    final sortedEntries = cacheEntries.entries.toList()
      ..sort((a, b) => a.value.compareTo(b.value));
    
    final entriesToRemove = (sortedEntries.length * 0.5).ceil();
    for (int i = 0; i < entriesToRemove && i < sortedEntries.length; i++) {
      await prefs.remove(sortedEntries[i].key);
      cleanedCount++;
    }
    
    DebugUtils.logLazy(() => '🧹 Emergency cleanup removed $cleanedCount cache entries');
  } catch (e) {
    DebugUtils.logLazy(() => '❌ Emergency cache cleanup failed: $e');
  }
}



void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock phones to portrait; tablets use system default (all orientations).
  // On iOS the Info.plist ~ipad key already declares landscape for iPads.
  final isTablet = WidgetsBinding.instance.platformDispatcher.views.first
          .physicalSize
          .shortestSide /
      WidgetsBinding.instance.platformDispatcher.views.first.devicePixelRatio >=
      600;
  await SystemChrome.setPreferredOrientations(
    isTablet
        ? [] // let the system / Info.plist decide for tablets
        : [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );

  // Configure system UI overlay to extend app background over status bar and navigation bar
  _setSystemUIOverlayStyle();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Ensure user is signed in (anonymous)
  await _ensureSignedIn();
  await PeriodCacheService.init();
  runApp(TempHist());
}

void _setSystemUIOverlayStyle() {
  if (io.Platform.isIOS) {
    // iOS-specific configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark, // Light text on dark background
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    );
  } else if (io.Platform.isAndroid) {
    // Android-specific configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light, // Light icons/text
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    );
  } else {
    // For other platforms, use a default configuration
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: Colors.transparent,
      ),
    );
  }
}

Future<void> _ensureSignedIn() async {
  if (FirebaseAuth.instance.currentUser == null) {
    await AuthService.signInAnonymously(maxRetries: 3, rethrowOnFailure: false);
  }
}

class TempHist extends StatelessWidget {
  const TempHist({super.key});

  @override
  Widget build(BuildContext context) {
    // Ensure system UI overlay is set correctly
    _setSystemUIOverlayStyle();
    
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: kAppTitle,
      home: const TemperatureScreen(),
      // Add a custom loading screen theme
      theme: ThemeData(
        scaffoldBackgroundColor: kBackgroundColour,
        // This helps prevent the white flash during initialization
        colorScheme: ColorScheme.fromSeed(
          seedColor: kAccentColour,
          brightness: Brightness.dark,
        ),
      ),
    );
  }
}

class TemperatureScreen extends StatefulWidget {
  final Future<Map<String, dynamic>?>? testFuture;

  const TemperatureScreen({super.key, this.testFuture});

  @override
  TemperatureScreenState createState() => TemperatureScreenState();
}

class TemperatureScreenState extends State<TemperatureScreen> with WidgetsBindingObserver {
  // Temperature unit preference (°C / °F).
  final TemperatureUnitService _unitService = TemperatureUnitService();
  bool get _isFahrenheit => _unitService.isFahrenheit.value;

  // Location is managed by the LocationService; these getters provide
  // backward-compatible access throughout the class.
  final LocationService _locationService = LocationService();
  String get _determinedLocation => _locationService.determinedLocation;
  String get _displayLocation => _locationService.displayLocation;
  bool get _isLocationDetermined => _locationService.isLocationDetermined;

  // Track app initialization state
  bool _isAppInitialized = false;
  bool _splashScreenMinTimeElapsed = false;
  Timer? _splashScreenTimer;
  final Completer<void> _splashCompleter = Completer<void>();

  // Guards auto-opening of the location selector on first launch with no GPS.
  bool _onboardingCheckComplete = false;
  bool _locationSelectorAutoOpened = false;

  // Simulation state for testing
  bool _simulateAverageFailure = AppConfig.defaultSimulateAverageFailure;
  bool _simulateTrendFailure = AppConfig.defaultSimulateTrendFailure;
  bool _simulateSummaryFailure = AppConfig.defaultSimulateSummaryFailure;

  geo.Position? get _lastPosition => _locationService.lastPosition;

  // Incremented whenever the location/unit changes so in-flight prefetch
  // polls for the old configuration can detect they are stale and bail out.
  int _prefetchGeneration = 0;

  // Tracks the date identifier (MM-DD) of the last data load so we can
  // detect midnight rollovers and reload all period pages.
  String _lastDateIdentifier = '';

  // Network connectivity state
  bool _isOnline = true;
  StreamSubscription<List<ConnectivityResult>>? _connectivitySubscription;

  // Memory management
  int _memoryCleanupCount = 0;

  // Page view for period switching (daily / weekly / monthly / yearly)
  late final PageController _pageController;
  final ValueNotifier<int> _pageIndexNotifier = ValueNotifier<int>(0);
  static const List<String> _periodKeys = ['daily', 'week', 'month', 'year'];
  bool _isSharing = false;
  final GlobalKey _dailyRepaintKey = GlobalKey();
  final GlobalKey _weekRepaintKey = GlobalKey();
  final GlobalKey _monthRepaintKey = GlobalKey();
  final GlobalKey _yearRepaintKey = GlobalKey();
  late final ScrollController _dailyScrollController;
  late final ScrollController _weekScrollController;
  late final ScrollController _monthScrollController;
  late final ScrollController _yearScrollController;
  final ValueNotifier<double> _scrollOffsetNotifier = ValueNotifier(0.0);
  ScrollController? _activeScrollController;
  final _dailyPageKey = GlobalKey<PeriodPageState>();
  final _weekPageKey = GlobalKey<PeriodPageState>();
  final _monthPageKey = GlobalKey<PeriodPageState>();
  final _yearPageKey = GlobalKey<PeriodPageState>();

  // Onboarding
  bool _hasSeenOnboarding = true; // default true to avoid flash during async check

  // Swipe coachmark
  bool _coachmarkPending = false;
  bool _showSwipeCoachmark = false;
  bool _coachmarkFadingOut = false;

  /// Resets scroll positions on all period pages to the top and clears the
  /// collapsed-header state. Call whenever the content is about to reload.
  void _resetScrollPositions() {
    _scrollOffsetNotifier.value = 0.0;
    for (final c in [
      _dailyScrollController,
      _weekScrollController,
      _monthScrollController,
      _yearScrollController,
    ]) {
      if (c.hasClients) c.jumpTo(0);
    }
  }

  /// Called whenever [_locationService] notifies listeners.
  void _onLocationChanged() {
    _resetScrollPositions();
    if (mounted) setState(() {});
  }

  void _onUnitChanged() {
    // The API returns different data (especially summaries) depending on the
    // unit.  Clear the in-memory cache so stale data is not served.
    // PeriodPage widgets detect the isFahrenheit prop change via
    // didUpdateWidget and re-fetch automatically.
    TemperatureService.clearCache();
    _resetScrollPositions();
    if (mounted) {
      _prefetchGeneration++;
      setState(() {});
      _prefetchPeriodData();
    }
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _pageController = PageController();
    _dailyScrollController = ScrollController();
    _weekScrollController = ScrollController();
    _monthScrollController = ScrollController();
    _yearScrollController = ScrollController();
    _attachScrollController(_dailyScrollController);

    // Debug mode detection logging
    DebugUtils.logLazy(() => '🔧 Debug mode detection:');
    DebugUtils.logLazy(() => '  - kDebugMode: $kDebugMode');
    DebugUtils.logLazy(() => '  - AppConfig.isDebugMode: ${AppConfig.isDebugMode}');
    DebugUtils.logLazy(() => '  - AppConfig.enableDebugUI: ${AppConfig.enableDebugUI}');
    DebugUtils.logLazy(() => '  - AppConfig.shouldShowDebugFeatures: ${AppConfig.shouldShowDebugFeatures}');
    
    // Load temperature unit preference (°C / °F) and rebuild on change.
    _unitService.load();
    _unitService.isFahrenheit.addListener(_onUnitChanged);

    // Listen to location changes to trigger UI rebuilds
    _locationService.addListener(_onLocationChanged);
    _locationService.onSignificantLocationChange = _refreshLocationAndData;

    // Start network connectivity monitoring
    _startConnectivityMonitoring();

    // Start minimum splash screen timer
    _startSplashScreenTimer();
    
    // If we have a test future, skip async initialization — PeriodPage
    // handles its own data loading when a location is set.
    if (widget.testFuture != null) {
      return;
    }

    // Initialize with location determination; PeriodPage widgets self-load
    // once a non-empty location is passed to them.
    _initializeApp();

    // Check whether to show the one-time onboarding flow
    _checkOnboarding();

    // Check whether to show the one-time swipe coachmark
    _checkSwipeCoachmark();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _pageController.dispose();
    _unitService.isFahrenheit.removeListener(_onUnitChanged);
    _locationService.removeListener(_onLocationChanged);
    _locationService.dispose();
    _connectivitySubscription?.cancel();
    _connectivitySubscription = null;
    _splashScreenTimer?.cancel();
    _splashScreenTimer = null;
    _pageIndexNotifier.dispose();
    _dailyScrollController.dispose();
    _weekScrollController.dispose();
    _monthScrollController.dispose();
    _yearScrollController.dispose();
    _scrollOffsetNotifier.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    if (state == AppLifecycleState.resumed) {
      DebugUtils.logLazy(() => 'App resumed - checking if location or date needs refresh');
      _checkAndRefreshLocationIfNeeded();
      _checkAndRefreshDataIfDateChanged();
      // Cleanup expired cache on resume
      _performMemoryCleanup();
    } else if (state == AppLifecycleState.paused) {
      DebugUtils.logLazy(() => 'App paused - performing memory cleanup');
      _performAggressiveMemoryCleanup();
    } else if (state == AppLifecycleState.detached) {
      DebugUtils.logLazy(() => 'App detached - performing final cleanup');
      _performAggressiveMemoryCleanup();
    }
  }

  Future<void> _initializeApp() async {
    if (widget.testFuture != null) {
      setState(() => _isAppInitialized = true);
      return;
    }

    DebugUtils.verboseLazy(() => 'Initializing app');

    await _cleanupExpiredCache();
    await _determineLocation();

    // Record the current date so we can detect midnight rollovers.
    _lastDateIdentifier = _currentDateIdentifier();

    if (_splashScreenMinTimeElapsed) {
      _onAppInitialized();
    } else {
      _waitForSplashScreenAndInitialize();
    }

    // PeriodPage widgets self-load once _determinedLocation becomes non-empty
    // (via didUpdateWidget). Pre-warm caches for the other periods in the
    // background.
    _prefetchPeriodData();

    _startListeningToLocationChanges();

    DebugUtils.verboseLazy(() => 'App initialization completed - location: $_determinedLocation');
  }

  Future<void> _checkAndRefreshLocationIfNeeded() async {
    if (_locationService.isLocationStale()) {
      await _refreshLocationAndData();
    }
  }

  /// Check if the calendar date has rolled over since last load and reload
  /// all period pages if so (e.g. after midnight when the app is resumed).
  void _checkAndRefreshDataIfDateChanged() {
    if (_lastDateIdentifier.isEmpty) return;
    final current = _currentDateIdentifier();
    if (current != _lastDateIdentifier) {
      DebugUtils.logLazy(() => 'Date changed ($_lastDateIdentifier → $current), reloading all periods');
      _lastDateIdentifier = current;
      _reloadAllPeriodPages();
    } else {
      DebugUtils.logLazy(() => 'Date unchanged ($current), keeping current data');
    }
  }

  /// Computes the MM-DD identifier used for API calls, accounting for the
  /// "use yesterday" threshold.
  String _currentDateIdentifier() {
    final now = DateTime.now();
    final useYesterday = now.hour < kUseYesterdayHourThreshold;
    final dateToUse = useYesterday ? now.subtract(const Duration(days: 1)) : now;
    return dateIdentifier(dateToUse);
  }

  /// Force-reload every PeriodPage via its GlobalKey.
  void _reloadAllPeriodPages() {
    for (final key in [_dailyPageKey, _weekPageKey, _monthPageKey, _yearPageKey]) {
      key.currentState?.reload();
    }
  }

  Future<void> _refreshLocationAndData() async {
    DebugUtils.logLazy(() => 'Refreshing location and data...');

    final previousLocation = _determinedLocation;

    // Mark refreshing but keep location string so period pages don't flash empty
    _locationService.markRefreshing();

    // Determine new location — PeriodPage widgets will auto-reload via
    // didUpdateWidget when the location prop changes.
    await _determineLocation();

    DebugUtils.logLazy(() => 'Location refresh: $previousLocation → $_determinedLocation');
    _prefetchPeriodData();
  }

  // Cache expiration constants
  static const Duration _currentDateCacheExpiration = Duration(hours: 1);
  static const Duration _historicalDataCacheExpiration = Duration(hours: 24);
  static const Duration _summaryCacheExpiration = Duration(hours: 1);
  static const Duration _averageTrendCacheExpiration = Duration(hours: 6);

  Future<void> _clearCache() async {
    await _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      
      // Get all keys to find cache entries
      final keys = prefs.getKeys();
      
      // Clear chart data cache
      await prefs.remove('cachedChartData');
      
      // Clear API response caches (average, trend, summary)
      for (final key in keys) {
        if (key.startsWith('api_')) {
          await prefs.remove(key);
        }
      }
      
      // Clear temperature data caches
      for (final key in keys) {
        if (key.startsWith('tempData_')) {
          await prefs.remove(key);
        }
      }
      
      // Clear location cache
      await prefs.remove('cachedLocation');
      
      DebugUtils.logLazy(() => 'All cache cleared: chart data, API responses, temperature data, and location');
    }, 'clear cache');
  }

  /// Clean up expired cache entries
  Future<void> _cleanupExpiredCache() async {
    await _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      final keys = prefs.getKeys();
      final now = DateTime.now();
      int cleanedCount = 0;

      for (final key in keys) {
        if (key.startsWith('tempData_') || key.startsWith('api_')) {
          try {
            final cachedData = prefs.getString(key);
            if (cachedData != null) {
              final data = jsonDecode(cachedData) as Map<String, dynamic>;
              final timestamp = DateTime.fromMillisecondsSinceEpoch(data['timestamp'] as int);
              final age = now.difference(timestamp);
              
              Duration expiration;
              if (key.startsWith('tempData_')) {
                // Temperature data cache
                final year = data['year'] as int;
                final isCurrentYear = year == now.year;
                expiration = isCurrentYear ? _currentDateCacheExpiration : _historicalDataCacheExpiration;
              } else if (key.startsWith('api_')) {
                // API response cache
                final endpoint = data['endpoint'] as String;
                switch (endpoint) {
                  case 'summary':
                    expiration = _summaryCacheExpiration;
                    break;
                  case 'average':
                  case 'trend':
                    expiration = _averageTrendCacheExpiration;
                    break;
                  default:
                    expiration = Duration(hours: 1);
                }
              } else {
                continue; // Skip unknown cache types
              }

              if (age > expiration) {
                await prefs.remove(key);
                cleanedCount++;
              }
            }
          } catch (e) {
            // If we can't parse the data, remove it
            await prefs.remove(key);
            cleanedCount++;
          }
        }
      }

      if (cleanedCount > 0) {
        DebugUtils.logLazy(() => '🧹 Cleaned up $cleanedCount expired cache entries');
      }
    }, 'cleanup expired cache');
  }

  /// Check whether the onboarding flow should be shown (first launch only).
  Future<void> _checkOnboarding() async {
    if (kDebugMode) {
      await _safeSharedPreferencesOperation(() async {
        final prefs = await SharedPreferences.getInstance();
        await prefs.remove('has_seen_onboarding');
      }, 'reset onboarding flag');
    }

    final seen = await _safeSharedPreferencesOperation<bool>(() async {
      final prefs = await SharedPreferences.getInstance();
      return prefs.getBool('has_seen_onboarding') ?? false;
    }, 'load onboarding flag');

    if (seen == true) {
      if (mounted) {
        _onboardingCheckComplete = true;
        _maybeAutoOpenLocationSelector();
      }
      return;
    }

    if (mounted) {
      setState(() => _hasSeenOnboarding = false);
      _onboardingCheckComplete = true;
      // _hasSeenOnboarding is false here so _maybeAutoOpenLocationSelector will
      // not open the selector now; _completeOnboarding will call it instead.
    }
  }

  /// Mark onboarding as complete and return to the main screen.
  Future<void> _completeOnboarding() async {
    await _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('has_seen_onboarding', true);
    }, 'save onboarding flag');

    if (mounted) {
      setState(() => _hasSeenOnboarding = true);
      // Now that the main screen is visible, start the coachmark if it was
      // held back because data loaded while onboarding was still showing.
      _startCoachmarkIfPending();
      // If the app had no location when it started, open the selector now
      // that the user has finished onboarding.
      _maybeAutoOpenLocationSelector();
    }
  }

  /// Check whether the swipe coachmark should be shown (first launch only).
  Future<void> _checkSwipeCoachmark() async {
    // In debug builds, reset so the coachmark is always visible for testing.
    if (kDebugMode) {
      await _safeSharedPreferencesOperation(() async {
        final prefs = await SharedPreferences.getInstance();
        await prefs.remove('swipeCoachmarkShown');
      }, 'reset swipe coachmark flag');
    }

    final shown = await _safeSharedPreferencesOperation<bool>(() async {
      final prefs = await SharedPreferences.getInstance();
      return prefs.getBool('swipeCoachmarkShown') ?? false;
    }, 'load swipe coachmark flag');

    if (shown == true) return;

    // Mark as pending — will be shown once the chart finishes loading.
    if (mounted) _coachmarkPending = true;
  }

  /// Show the coachmark now and start the auto-dismiss timer.
  /// Called via PeriodPage's onDataLoaded callback and from
  /// [_completeOnboarding].  Does nothing if the user is still in the
  /// onboarding flow — the coachmark stays pending and is started once
  /// onboarding completes.
  void _startCoachmarkIfPending() {
    if (!_coachmarkPending) return;
    if (!_hasSeenOnboarding) return;
    _coachmarkPending = false;
    if (mounted) {
      setState(() {
        _showSwipeCoachmark = true;
        _coachmarkFadingOut = false;
      });
      Future.delayed(const Duration(seconds: 8), _dismissCoachmark);
    }
  }

  /// Fade out and permanently dismiss the swipe coachmark.
  void _dismissCoachmark() {
    if (!_showSwipeCoachmark || _coachmarkFadingOut) return;
    if (mounted) {
      setState(() {
        _coachmarkFadingOut = true;
      });
    }
    _safeSharedPreferencesOperation(() async {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('swipeCoachmarkShown', true);
    }, 'save swipe coachmark shown');
  }


  Future<void> _determineLocation() async {
    await _locationService.determineLocation();
  }

  /// Pre-warm the in-memory and Hive caches for all four periods in parallel.
  /// PeriodPage widgets that have already loaded will hit the in-memory cache
  /// instead of making a duplicate network call.
  Future<void> _prefetchPeriodData() async {
    if (!_isLocationDetermined || _determinedLocation.isEmpty) return;

    final dateInfo = _getCurrentDateAndLocation(_determinedLocation);
    final identifier = dateInfo['mmdd']!;
    final location = _determinedLocation;
    final service = TemperatureService();
    const periods = ['daily', 'week', 'month', 'year'];

    final generation = _prefetchGeneration;
    bool isCancelled() => _prefetchGeneration != generation;

    final isAtGps = _locationService.isAtGpsCity(location);
    final lat = isAtGps ? _lastPosition?.latitude : null;
    final lon = isAtGps ? _lastPosition?.longitude : null;

    DebugUtils.logLazy(() => 'Prefetching period data in parallel for $location ($identifier)');

    await Future.wait(
      periods.map((period) async {
        if (isCancelled()) return;
        try {
          DebugUtils.logLazy(() => 'Prefetching $period data');
          final unitGroup = _isFahrenheit ? 'fahrenheit' : null;
          final data = await service.fetchPeriodData(
            period,
            location,
            identifier,
            unitGroup: unitGroup,
            isCancelled: isCancelled,
          );
          if (!isCancelled() && lat != null && lon != null) {
            await PeriodCacheService.put(period, lat, lon, identifier, data,
                unitGroup: unitGroup);
          }
        } catch (e) {
          DebugUtils.logLazy(() => 'Prefetch $period failed: $e');
        }
      }),
    );
  }

  void _startSplashScreenTimer() {
    // Skip splash screen timer in test mode
    if (widget.testFuture != null) {
      _splashScreenMinTimeElapsed = true;
      if (!_splashCompleter.isCompleted) _splashCompleter.complete();
      return;
    }

    // Show splash screen for minimum 2 seconds to prevent white flash
    _splashScreenTimer = Timer(const Duration(seconds: 2), () {
      if (mounted) {
        setState(() {
          _splashScreenMinTimeElapsed = true;
        });
        if (!_splashCompleter.isCompleted) _splashCompleter.complete();
      }
    });
  }

  Future<void> _waitForSplashScreenAndInitialize() async {
    // Skip in test mode
    if (widget.testFuture != null) {
      setState(() {
        _isAppInitialized = true;
      });
      return;
    }

    await _splashCompleter.future;
    if (mounted) {
      _onAppInitialized();
    }
  }

  /// Sets [_isAppInitialized] then checks whether the location selector should
  /// be auto-opened (deferred until we also know the onboarding state).
  void _onAppInitialized() {
    setState(() {
      _isAppInitialized = true;
    });
    _maybeAutoOpenLocationSelector();
  }

  /// Opens the location selector automatically when:
  ///  - the app is fully initialised,
  ///  - we know whether onboarding is needed (race-condition guard),
  ///  - onboarding has already been seen (so we don't open over it), AND
  ///  - GPS produced no result and there is no saved location history.
  ///
  /// When onboarding *has not* been seen, [_completeOnboarding] will call this
  /// once the user finishes, at which point all conditions will be satisfied.
  void _maybeAutoOpenLocationSelector() {
    if (_locationSelectorAutoOpened) return;
    if (!_isAppInitialized) return;
    if (!_onboardingCheckComplete) return;
    if (!_hasSeenOnboarding) return;
    if (!_locationService.locationPermissionDenied) return;

    _locationSelectorAutoOpened = true;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) _showRequiredLocationSelector();
    });
  }








  Future<void> _handleRefresh() async {
    DebugUtils.logLazy(() => 'Full refresh triggered');

    TemperatureService.clearCache();

    if (AppConfig.enableEndpointFailureSimulation) {
      await _clearCache();
    }

    if (!mounted) return;
    _locationService.reset();

    await _initializeApp();
  }

  /// Force refresh without using cache (for debugging/testing)
  Future<void> _handleForceRefresh() async {
    DebugUtils.logLazy(() => 'Force refresh triggered - clearing all cache');

    TemperatureService.clearCache();
    await _clearCache();

    if (!mounted) return;
    _locationService.reset();
    await _initializeApp();
  }

  /// Clear only location cache (for testing different locations in Simulator)
  Future<void> _handleLocationRefresh() async {
    DebugUtils.logLazy(() => 'Location refresh triggered - clearing location cache only');

    await _locationService.clearCache();

    if (!mounted) return;
    _locationService.reset();
    await _initializeApp();
  }

  /// Opens the settings sheet.
  void _showSettings() {
    SettingsSheet.show(
      context,
      isFahrenheit: _isFahrenheit,
      onUnitChanged: (value) => _unitService.setFahrenheit(value),
      onOpenLocationSelector: _showLocationSelector,
    );
  }

  /// Opens the location selector bottom sheet.
  void _showLocationSelector() {
    LocationSelectorSheet.show(
      context,
      gpsLocation: _locationService.gpsLocation,
      selectedLocation: _determinedLocation,
      onLocationSelected: _onLocationSelected,
    );
  }

  /// Opens the location selector without a close button, used on first launch
  /// when no location has been determined, so the user must pick a city.
  void _showRequiredLocationSelector() {
    LocationSelectorSheet.show(
      context,
      gpsLocation: _locationService.gpsLocation,
      selectedLocation: _determinedLocation,
      onLocationSelected: _onLocationSelected,
      canDismiss: false,
    );
  }

  /// Called when the user picks a location from the selector sheet.
  Future<void> _onLocationSelected(String apiLocation) async {
    if (apiLocation == _determinedLocation) return;

    final currentPage = _pageIndexNotifier.value;
    final currentPeriod = _periodKeys[currentPage];
    DebugUtils.logLazy(() =>
        '📍 Location switch: $_determinedLocation → $apiLocation '
        '(on $currentPeriod page, gps: ${_locationService.gpsLocation})');

    // Purge the in-memory service cache so stale data for the old location
    // is never served to the new fetch.
    TemperatureService.clearCache();
    _prefetchGeneration++;

    await _locationService.setManualLocation(apiLocation);

    // PeriodPage widgets detect the location prop change via didUpdateWidget
    // and re-fetch automatically.  Pre-warm caches for other periods.
    if (!mounted) return;
    _prefetchPeriodData();
  }

  /// Test date change detection (for debugging)
  void _handleTestDateChange() {
    DebugUtils.logLazy(() => 'Test date change triggered - simulating date change detection');
    // Pretend the last load was for a different date, then run the check.
    _lastDateIdentifier = '00-00';
    _checkAndRefreshDataIfDateChanged();
  }

  /// Clear all cache (for debugging)
  Future<void> _handleClearCache() async {
    DebugUtils.logLazy(() => 'Clear cache triggered - clearing all cached data');
    
    // Clear all cache
    await _clearCache();
    
    // Show feedback only if widget is still mounted
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Cache cleared successfully'),
          duration: Duration(seconds: 1),
        ),
      );
    }
  }

  Widget _buildGradientBackground() {
    return SizedBox.expand(
      child: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              kBackgroundColour, // Top color
              kBackgroundColourDark, // Bottom color
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildVersionSection() {
    return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Debug Info:',
              style: TextStyle(
                color: kGreyLabelColour,
                fontSize: kFontSizeBody - 2,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              'Version: ${AppConfig.fullVersion}',
              style: TextStyle(
                color: kGreyLabelColour,
                fontSize: kFontSizeBody - 3,
                fontWeight: FontWeight.w400,
              ),
            ),
            Text(
              'Release: ${AppConfig.releaseDate}',
              style: TextStyle(
                color: kGreyLabelColour,
                fontSize: kFontSizeBody - 3,
                fontWeight: FontWeight.w400,
              ),
            ),
          ],
        );
  }

  Widget _buildDebugToggleSection() {
    return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Debug Mode - Simulate Endpoint Failures:',
              style: TextStyle(
                color: kGreyLabelColour,
                fontSize: kFontSizeBody - 1,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 8),
            // Use Wrap for responsive button layout
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _buildDebugToggleButton('Average', 'average'),
                _buildDebugToggleButton('Trend', 'trend'),
                _buildDebugToggleButton('Summary', 'summary'),
                _buildResetAllButton(),
                _buildForceRefreshButton(),
                _buildLocationRefreshButton(),
                _buildTestDateChangeButton(),
                _buildClearCacheButton(),
              ],
            ),
            if (AppConfig.enableEndpointFailureSimulation) ...[
              const SizedBox(height: 8),
              Text(
                'Simulation Active: ${_simulateAverageFailure ? "Average" : ""}${_simulateTrendFailure ? "${_simulateAverageFailure ? ", " : ""}Trend" : ""}${_simulateSummaryFailure ? "${(_simulateAverageFailure || _simulateTrendFailure) ? ", " : ""}Summary" : ""}',
                style: TextStyle(
                  color: kAccentColour,
                  fontSize: kFontSizeBody - 2,
                  fontWeight: FontWeight.w400,
                ),
              ),
            ],
          ],
        );
  }

  Widget _buildDebugToggleButton(String label, String endpoint) {
    bool isSimulating = false;
    
    switch (endpoint) {
      case 'average':
        isSimulating = _simulateAverageFailure;
        break;
      case 'trend':
        isSimulating = _simulateTrendFailure;
        break;
      case 'summary':
        isSimulating = _simulateSummaryFailure;
        break;
    }
    
    return GestureDetector(
      onTap: () async {
        setState(() {
          switch (endpoint) {
            case 'average':
              _simulateAverageFailure = !_simulateAverageFailure;
              break;
            case 'trend':
              _simulateTrendFailure = !_simulateTrendFailure;
              break;
            case 'summary':
              _simulateSummaryFailure = !_simulateSummaryFailure;
              break;
          }
        });
        
        // Show feedback
        if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${isSimulating ? 'Disabled' : 'Enabled'} $label failure simulation'),
            duration: const Duration(seconds: 1),
          ),
        );
        }
        
        // If we're enabling a simulation, trigger a refresh to see the failure
        if (!isSimulating) {
          // Clear cache when enabling simulation to ensure fresh data loading
          await _clearCache();
          if (mounted) {
          _handleRefresh();
          }
        }
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: isSimulating ? kAccentColour : kGreyLabelColour.withValues(alpha: 0.3),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          label,
          style: TextStyle(
            color: isSimulating ? Colors.white : kGreyLabelColour,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  Widget _buildResetAllButton() {
    return GestureDetector(
      onTap: () async {
        setState(() {
          _simulateAverageFailure = false;
          _simulateTrendFailure = false;
          _simulateSummaryFailure = false;
        });
        // Show feedback
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('All failure simulations reset'),
            duration: const Duration(seconds: 1),
          ),
        );
        // Clear cache and refresh to ensure clean state
        await _clearCache();
        if (mounted) _handleRefresh();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: kGreyLabelColour.withValues(alpha: 0.3),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          'Reset All',
          style: TextStyle(
            color: kGreyLabelColour,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  Widget _buildForceRefreshButton() {
    return GestureDetector(
      onTap: () {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Force refresh - clearing all cache'),
            duration: Duration(seconds: 1),
          ),
        );
        _handleForceRefresh();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: kAccentColour.withValues(alpha: 0.2),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          'Force Refresh',
          style: TextStyle(
            color: kAccentColour,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  Widget _buildLocationRefreshButton() {
    return GestureDetector(
      onTap: () {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Location refresh - clearing location cache'),
            duration: Duration(seconds: 1),
          ),
        );
        _handleLocationRefresh();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: kGreyLabelColour.withValues(alpha: 0.2),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          'Location Refresh',
          style: TextStyle(
            color: kGreyLabelColour,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  Widget _buildTestDateChangeButton() {
    return GestureDetector(
      onTap: () {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Simulating date change - clearing data and reloading...'),
            duration: Duration(seconds: 2),
          ),
        );
        _handleTestDateChange();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: Colors.orange.withValues(alpha: 0.2),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          'Test Date Change',
          style: TextStyle(
            color: Colors.orange,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  Widget _buildClearCacheButton() {
    return GestureDetector(
      onTap: () {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Clearing all cache...'),
            duration: Duration(seconds: 1),
          ),
        );
        _handleClearCache();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
        decoration: BoxDecoration(
          color: Colors.red.withValues(alpha: 0.2),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Text(
          'Clear Cache',
          style: TextStyle(
            color: Colors.red,
            fontSize: kFontSizeBody - 2,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }

  /// Top-level layout: fixed header (title + debug) and swipeable PageView below.
  Widget _buildPageLayout(BuildContext context, double chartHeight) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final screenWidth = MediaQuery.of(context).size.width;
        final isTablet = screenWidth >= 768;
        final maxContentWidth = isTablet ? 650.0 : constraints.maxWidth;
        final contentWidth = constraints.maxWidth > maxContentWidth ? maxContentWidth : constraints.maxWidth;
        final horizontalMargin = isTablet ? (constraints.maxWidth - contentWidth) / 2 : 0.0;

        return SizedBox(
          width: constraints.maxWidth,
          child: Center(
            child: Container(
              width: contentWidth,
              margin: EdgeInsets.symmetric(horizontal: horizontalMargin),
              child: PageView(
                controller: _pageController,
                onPageChanged: (index) {
                  _pageIndexNotifier.value = index;
                  _dismissCoachmark();
                  final controllers = [
                    _dailyScrollController,
                    _weekScrollController,
                    _monthScrollController,
                    _yearScrollController,
                  ];
                  _attachScrollController(controllers[index]);
                },
                children: [
                  // Page 0: Daily
                  _buildPeriodPage(
                    context,
                    pageIndex: 0,
                    pageKey: _dailyPageKey,
                    repaintKey: _dailyRepaintKey,
                    periodKey: 'daily',
                    periodLabel: 'daily',
                    scrollController: _dailyScrollController,
                    onDataLoaded: _startCoachmarkIfPending,
                  ),
                  // Page 1: Weekly
                  _buildPeriodPage(
                    context,
                    pageIndex: 1,
                    pageKey: _weekPageKey,
                    repaintKey: _weekRepaintKey,
                    periodKey: 'week',
                    periodLabel: 'Past week',
                    scrollController: _weekScrollController,
                  ),
                  // Page 2: Monthly
                  _buildPeriodPage(
                    context,
                    pageIndex: 2,
                    pageKey: _monthPageKey,
                    repaintKey: _monthRepaintKey,
                    periodKey: 'month',
                    periodLabel: 'Past month',
                    scrollController: _monthScrollController,
                  ),
                  // Page 3: Yearly
                  _buildPeriodPage(
                    context,
                    pageIndex: 3,
                    pageKey: _yearPageKey,
                    repaintKey: _yearRepaintKey,
                    periodKey: 'year',
                    periodLabel: 'Past year',
                    scrollController: _yearScrollController,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildPageHeader(BuildContext context) {
    return ValueListenableBuilder<double>(
      valueListenable: _scrollOffsetNotifier,
      builder: (context, offset, _) {
        const collapseThreshold = 80.0;
        final t = (offset / collapseThreshold).clamp(0.0, 1.0);

        return ValueListenableBuilder<int>(
          valueListenable: _pageIndexNotifier,
          builder: (context, pageIndex, _) {
            final locationColour = _locationColour;
            final headerText = _displayLocation.isNotEmpty
                ? _displayLocation
                : (_determinedLocation.isNotEmpty
                    ? _determinedLocation
                    : 'Loading location...');

            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: EdgeInsets.only(
                    top: kContentVerticalPadding,
                    bottom: kTitleRowBottomPadding,
                    left: kScreenPadding + kContentHorizontalMargin,
                    right: kScreenPadding + kContentHorizontalMargin,
                  ),
                  child: Row(
                    children: [
                      // Cross-fade: dots (t=0) → location+period (t=1)
                      Expanded(
                        child: Stack(
                          children: [
                            // Location + period — always laid out (sets Stack height),
                            // fades in as user scrolls.
                            Opacity(
                              opacity: t,
                              child: IgnorePointer(
                                ignoring: t < 0.5,
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    GestureDetector(
                                      onTap: _isLocationDetermined
                                          ? _showLocationSelector
                                          : null,
                                      behavior: HitTestBehavior.opaque,
                                      child: Text(
                                        headerText,
                                        style: TextStyle(
                                          color: locationColour,
                                          fontSize: kFontSizeLocation,
                                          fontWeight: FontWeight.w600,
                                          letterSpacing: 0.5,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                        maxLines: 1,
                                      ),
                                    ),
                                    GestureDetector(
                                      onTap: _isSharing
                                          ? null
                                          : () => _shareCurrentPeriod(pageIndex),
                                      behavior: HitTestBehavior.opaque,
                                      child: Text(
                                        _buildPeriodHeaderLabel(pageIndex),
                                        style: const TextStyle(
                                          color: kGreyLabelColour,
                                          fontSize: kFontSizeBody - 2,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                        maxLines: 1,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            // Dots + coachmark — Positioned.fill so they don't
                            // affect Stack height; centred to align with the
                            // settings/share icons in the Row; fade out on scroll.
                            Positioned.fill(
                              child: Align(
                                alignment: Alignment.centerLeft,
                                child: Opacity(
                                  opacity: (1.0 - t).clamp(0.0, 1.0),
                                  child: IgnorePointer(
                                    ignoring: t > 0.5,
                                    child: _buildDotsRow(pageIndex),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 8),
                      // Share icon — always visible
                      GestureDetector(
                        onTap: _isSharing ? null : () => _shareCurrentPeriod(pageIndex),
                        behavior: HitTestBehavior.opaque,
                        child: Padding(
                          // No GlobalKey here — _buildPageHeader is called once
                          // per page, so 4 Padding widgets would share one key.
                          // iPad popover falls back to Rect.fromLTWH(0,0,1,1).
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                          child: _isSharing
                              ? SizedBox(
                                  width: kIconSize + 6,
                                  height: kIconSize + 6,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                    color: kGreyLabelColour.withValues(alpha: 0.7),
                                  ),
                                )
                              : Icon(
                                  Icons.ios_share,
                                  color: kGreyLabelColour.withValues(alpha: 0.7),
                                  size: kIconSize + 6,
                                ),
                        ),
                      ),
                      // Settings gear — always visible
                      GestureDetector(
                        onTap: _showSettings,
                        behavior: HitTestBehavior.opaque,
                        child: Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                          child: Icon(
                            Icons.settings,
                            color: kGreyLabelColour.withValues(alpha: 0.7),
                            size: kIconSize + 8,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                if (AppConfig.shouldShowDebugFeatures) ...[
                  _buildDebugPadding(context, _buildDebugToggleSection()),
                  _buildDebugPadding(context, _buildVersionSection()),
                ],
              ],
            );
          },
        );
      },
    );
  }

  Widget _buildScrollablePageBody(
    BuildContext context,
    Widget content, {
    Widget Function(Widget child)? wrapWithRefresh,
    ScrollController? scrollController,
  }) {
    final scrollView = SingleChildScrollView(
      controller: scrollController,
      physics: const AlwaysScrollableScrollPhysics(),
      child: content,
    );
    final scrollable =
        wrapWithRefresh != null ? wrapWithRefresh(scrollView) : scrollView;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildPageHeader(context),
        Expanded(child: scrollable),
      ],
    );
  }

  Widget _buildExternalRefreshIndicator({
    required Widget child,
    required Future<void> Function() onRefresh,
  }) {
    if (widget.testFuture != null) {
      return child;
    }

    return RefreshIndicator(
      onRefresh: onRefresh,
      color: kAccentColour,
      backgroundColor: kBackgroundColour,
      child: child,
    );
  }

  Future<void> _shareCurrentPeriod(int pageIndex) async {
    setState(() => _isSharing = true);
    try {
      final String periodKey;
      switch (pageIndex) {
        case 0:
          periodKey = 'daily';
        case 1:
          periodKey = 'week';
        case 2:
          periodKey = 'month';
        case 3:
          periodKey = 'year';
        default:
          return;
      }

      final dateInfo = _getCurrentDateAndLocation(_determinedLocation);
      final dateToUse = DateTime.parse(dateInfo['date']!);
      final identifier = dateIdentifier(dateToUse);
      final refYear = dateToUse.year;
      final unit = _isFahrenheit ? 'fahrenheit' : 'celsius';

      final shareService = ShareService();

      final shareUrl = await shareService.createShare(
        location: _determinedLocation,
        period: periodKey,
        identifier: identifier,
        refYear: refYear,
        unit: unit,
      );

      // Clear the spinner before opening the native sheet. The share future
      // may never resolve on iOS if the user dismisses without selecting an
      // action, which would leave _isSharing stuck as true indefinitely.
      if (mounted) setState(() => _isSharing = false);

      await shareService.share(
        shareUrl: shareUrl,
        shareButtonKey: null,
      );
    } catch (e) {
      DebugUtils.logLazy(() => 'Share failed: $e');
      if (mounted) setState(() => _isSharing = false);
    }
  }

  Widget _buildDotsRow(int pageIndex) {
    return Row(
      children: [
        for (int i = 0; i < _periodKeys.length; i++) ...[
          if (i > 0) const SizedBox(width: 8),
          Container(
            width: i == pageIndex ? 12 : 10,
            height: i == pageIndex ? 12 : 10,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: i == pageIndex
                  ? kBarCurrentYearColour
                  : kGreyLabelColour.withValues(alpha: 0.4),
            ),
          ),
        ],
        const SizedBox(width: 10),
        AnimatedOpacity(
          opacity: (_showSwipeCoachmark && !_coachmarkFadingOut) ? 1.0 : 0.0,
          duration: const Duration(milliseconds: 600),
          onEnd: () {
            if (_coachmarkFadingOut && mounted) {
              setState(() => _showSwipeCoachmark = false);
            }
          },
          child: _DotsSwipeHint(
            running: _showSwipeCoachmark && !_coachmarkFadingOut,
          ),
        ),
      ],
    );
  }

  /// Location row + period heading row shown at the top of each page's
  /// scrollable content. This is inside the RepaintBoundary so both elements
  /// appear in the share image.
  Widget _buildLocationAndHeadingContent(int pageIndex) {
    final locationColour = _locationColour;
    final headerText = _displayLocation.isNotEmpty
        ? _displayLocation
        : (_determinedLocation.isNotEmpty
            ? _determinedLocation
            : 'Loading location...');

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        GestureDetector(
          onTap: _isLocationDetermined ? _showLocationSelector : null,
          behavior: HitTestBehavior.opaque,
          child: Row(
            children: [
              Icon(
                Icons.location_on_outlined,
                color: locationColour.withValues(alpha: 0.8),
                size: kIconSize + 2,
              ),
              const SizedBox(width: 6),
              Expanded(
                child: Text(
                  headerText,
                  style: TextStyle(
                    color: locationColour,
                    fontSize: kFontSizeLocation,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0.5,
                  ),
                  overflow: TextOverflow.ellipsis,
                  maxLines: 1,
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: 4),
        Text(
          _buildPeriodHeaderLabel(pageIndex),
          style: const TextStyle(
            color: kTextPrimaryColour,
            fontSize: kFontSizeBody,
            fontWeight: FontWeight.w600,
          ),
          overflow: TextOverflow.ellipsis,
        ),
      ],
    );
  }

  void _attachScrollController(ScrollController controller) {
    _activeScrollController?.removeListener(_onActiveScrollChanged);
    _activeScrollController = controller;
    controller.addListener(_onActiveScrollChanged);
    _scrollOffsetNotifier.value =
        controller.hasClients ? controller.offset : 0.0;
  }

  void _onActiveScrollChanged() {
    if (_activeScrollController?.hasClients == true) {
      _scrollOffsetNotifier.value =
          _activeScrollController!.offset.clamp(0.0, double.infinity);
    }
  }

  Color get _locationColour {
    if (!_isLocationDetermined) return kGreyLabelColour.withValues(alpha: 0.4);
    switch (_locationService.locationSource) {
      case LocationSource.gps:
        // Green — your actual GPS location, matches the current-year bar.
        return kBarCurrentYearColour;
      case LocationSource.recentlyVisited:
        // Red — a city you've physically been to (in GPS history).
        // Red has more visual weight than blue, reflecting that personal history
        // is more relevant than an arbitrary popular-city selection.
        return kAccentColour;
      case LocationSource.manual:
        // Blue — a city chosen from the popular list with no GPS history.
        // Neutral, matches the average reference line in the chart.
        return kAverageColour;
    }
  }

  String _buildPeriodHeaderLabel(int pageIndex) {
    final dateInfo = _getCurrentDateAndLocation(_determinedLocation);
    final dateToUse = DateTime.parse(dateInfo['date']!);
    final displayDate = _formatDayMonth(dateToUse);

    switch (pageIndex) {
      case 0:
        return displayDate;
      case 1:
        return 'Week ending $displayDate';
      case 2:
        return 'Month ending $displayDate';
      case 3:
        return 'Year ending $displayDate';
      default:
        return displayDate;
    }
  }

  /// Builds a period page (daily, weekly, monthly, or yearly).
  /// All four periods use the same PeriodPage widget — the only difference
  /// is the periodKey/periodLabel and the daily page additionally wires up
  /// the coachmark callback.
  Widget _buildPeriodPage(
    BuildContext context, {
    required int pageIndex,
    required GlobalKey<PeriodPageState> pageKey,
    required GlobalKey repaintKey,
    required String periodKey,
    required String periodLabel,
    required ScrollController scrollController,
    VoidCallback? onDataLoaded,
  }) {
    final isAtGps = _locationService.isAtGpsCity(_determinedLocation);
    final lat = isAtGps ? _lastPosition?.latitude : null;
    final lon = isAtGps ? _lastPosition?.longitude : null;

    final sidePad = _standardHorizontalPadding();
    final content = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        RepaintBoundary(
          key: repaintKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: EdgeInsets.only(
                  left: sidePad,
                  right: sidePad,
                  bottom: kSectionBottomPadding,
                ),
                child: _buildLocationAndHeadingContent(pageIndex),
              ),
              PeriodPage(
                key: pageKey,
                periodKey: periodKey,
                periodLabel: periodLabel,
                location: _determinedLocation,
                displayLocation:
                    _displayLocation.isNotEmpty ? _displayLocation : null,
                latitude: lat,
                longitude: lon,
                useInternalScroll: false,
                isFahrenheit: _isFahrenheit,
                onDataLoaded: onDataLoaded,
              ),
            ],
          ),
        ),
      ],
    );
    return _buildScrollablePageBody(
      context,
      content,
      scrollController: scrollController,
      wrapWithRefresh: (child) => _buildExternalRefreshIndicator(
        child: child,
        onRefresh: () async {
          await pageKey.currentState?.refresh();
        },
      ),
    );
  }


  Widget _buildDebugPadding(BuildContext context, Widget child) {
    final leftPadding = _standardHorizontalPadding().clamp(0.0, double.infinity);
    final rightPadding = leftPadding;

    return Padding(
      padding: EdgeInsets.only(
        bottom: 8.0, // Reduced bottom padding for debug sections
        left: leftPadding,
        right: rightPadding,
      ),
      child: child,
    );
  }

  double _standardHorizontalPadding() => kScreenPadding + kContentHorizontalMargin;

  /// Start monitoring network connectivity
  void _startConnectivityMonitoring() {
    // Check initial connectivity status asynchronously without blocking
    () async {
      try {
        final initialResults = await Connectivity().checkConnectivity();
        if (mounted) {
          _isOnline = initialResults.any((result) =>
            result == ConnectivityResult.mobile ||
            result == ConnectivityResult.wifi ||
            result == ConnectivityResult.ethernet
          );
          DebugUtils.logLazy(() => '🌐 Initial connectivity status: ${_isOnline ? "online" : "offline"}');
        }
      } catch (e) {
        DebugUtils.logLazy(() => '⚠️ Failed to check initial connectivity: $e');
        // Default to online if check fails (already set to true by default)
      }
    }();

    // Start listening for changes immediately
    _connectivitySubscription = Connectivity().onConnectivityChanged.listen(
      (List<ConnectivityResult> results) {
        final wasOnline = _isOnline;
        _isOnline = results.any((result) =>
          result == ConnectivityResult.mobile ||
          result == ConnectivityResult.wifi ||
          result == ConnectivityResult.ethernet
        );

        DebugUtils.logLazy(() => '🌐 Network connectivity changed: ${_isOnline ? "online" : "offline"}');

        // If we just came back online and were offline, try to refresh data
        if (!wasOnline && _isOnline) {
          DebugUtils.logLazy(() => '🔄 Network restored, attempting to refresh data');
          _handleNetworkRestored();
        }

        // Update UI to reflect connectivity state (_isOnline was updated above)
        if (mounted) {
          DebugUtils.logLazy(() => '🌐 Updating UI for connectivity state: ${_isOnline ? "online" : "offline"}');
          setState(() {
            // _isOnline was already updated above — this triggers a rebuild.
          });
        }
      },
    );
  }

  /// Handle network restoration
  void _handleNetworkRestored() {
    DebugUtils.logLazy(() => '🔄 Network restored, reloading period data');
    _reloadAllPeriodPages();
  }

  /// Perform memory cleanup and data optimization
  /// Called on app lifecycle events (resume/pause/detach) instead of periodic timer
  void _performMemoryCleanup() {
    _memoryCleanupCount++;
    DebugUtils.logLazy(() => '🧹 Performing memory cleanup #$_memoryCleanupCount');

    try {
      _cleanupExpiredCache();
      DebugUtils.logLazy(() => '✅ Memory cleanup completed');
    } catch (e) {
      DebugUtils.logLazy(() => '❌ Memory cleanup failed: $e');
    }
  }

  /// Perform aggressive memory cleanup when app goes to background
  void _performAggressiveMemoryCleanup() {
    DebugUtils.logLazy(() => '🧹 Performing aggressive memory cleanup');

    try {
      _cleanupExpiredCache();
      DebugUtils.logLazy(() => '✅ Aggressive memory cleanup completed');
    } catch (e) {
      DebugUtils.logLazy(() => '❌ Aggressive memory cleanup failed: $e');
    }
  }

  void _startListeningToLocationChanges() {
    _locationService.startListeningToLocationChanges(
      isLoadingGuard: () => false,
    );
  }

  @override
  Widget build(BuildContext context) {
    // Ensure system UI overlay is set correctly
    _setSystemUIOverlayStyle();
    
    // Show splash screen while app is initializing OR minimum time hasn't elapsed
    // Skip splash screen in test mode
    if (widget.testFuture == null && (!_isAppInitialized || !_splashScreenMinTimeElapsed)) {
      return const SplashScreen();
    }

    if (!_hasSeenOnboarding) {
      return OnboardingScreen(
        onComplete: _completeOnboarding,
        unitService: _unitService,
      );
    }

    final double chartHeight = kChartHeight;

    Widget appContent = Scaffold(
      body: Stack(
        children: [
          // Gradient background fills the whole screen including system areas
          _buildGradientBackground(),
          // Foreground content with fixed header and swipeable pages
          SafeArea(
            bottom: false,
            child: _buildPageLayout(context, chartHeight),
          ),
        ],
      ),
    );

    // Wrap with AnnotatedRegion for mobile platforms
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light,
        // iOS uses statusBarBrightness, Android uses statusBarIconBrightness
        statusBarBrightness: io.Platform.isIOS ? Brightness.dark : null,
        statusBarIconBrightness: io.Platform.isIOS ? null : Brightness.light,
      ),
      child: appContent,
    );
  }

}

String _formatDayMonth(DateTime date) => date_utils.formatDateWithOrdinal(date);

/// Animated right-arrow hint shown inline with the page-indicator dots.
///
/// Slides a chevron to the right and fades it out, then snaps back and
/// repeats — identical timing to [SwipeGestureIndicator] but compact
/// (icon only, no text). The [running] flag stops the animation controller
/// when the parent hides this widget, avoiding unnecessary CPU use.
class _DotsSwipeHint extends StatefulWidget {
  final bool running;
  const _DotsSwipeHint({required this.running});

  @override
  State<_DotsSwipeHint> createState() => _DotsSwipeHintState();
}

class _DotsSwipeHintState extends State<_DotsSwipeHint>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _slide;
  late final Animation<double> _fade;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1400),
    );
    if (widget.running) _controller.repeat();

    _slide = TweenSequence([
      TweenSequenceItem(
        tween: Tween(begin: 0.0, end: 14.0)
            .chain(CurveTween(curve: Curves.easeInOut)),
        weight: 55,
      ),
      TweenSequenceItem(tween: ConstantTween(0.0), weight: 45),
    ]).animate(_controller);

    _fade = TweenSequence([
      TweenSequenceItem(tween: ConstantTween(1.0), weight: 40),
      TweenSequenceItem(
        tween: Tween(begin: 1.0, end: 0.0)
            .chain(CurveTween(curve: Curves.easeOut)),
        weight: 15,
      ),
      TweenSequenceItem(
        tween: Tween(begin: 0.0, end: 1.0)
            .chain(CurveTween(curve: Curves.easeIn)),
        weight: 10,
      ),
      TweenSequenceItem(tween: ConstantTween(1.0), weight: 35),
    ]).animate(_controller);
  }

  @override
  void didUpdateWidget(_DotsSwipeHint old) {
    super.didUpdateWidget(old);
    if (widget.running && !old.running) {
      _controller.repeat();
    } else if (!widget.running && old.running) {
      _controller.stop();
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (_, __) => Opacity(
        opacity: _fade.value,
        child: Transform.translate(
          offset: Offset(_slide.value, 0),
          child: Icon(
            Icons.chevron_right,
            color: kBarCurrentYearColour,
            size: kIconSize + 2,
          ),
        ),
      ),
    );
  }
}
