platform :ios, '15.0'

flutter_sdk_root = ENV['FLUTTER_ROOT'] or
  raise 'FLUTTER_ROOT env-var is not set; run `flutter` once or set it manually'

require File.join(flutter_sdk_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks!                       # or use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name == 'Pods-Runner'
      t.build_configurations.each do |c|
        if c.name == 'Release'
          c.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          c.build_settings['CODE_SIGN_STYLE'] = 'Manual'
        end
      end
    end
    if t.name == 'geocoding_ios'
      phase = t.resources_build_phase
      phase.files_references
           .select { |fr| fr.path.end_with?('PrivacyInfo.xcprivacy') }
           .each   { |fr| phase.remove_file_reference(fr) }
    end
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    flutter_additional_ios_build_settings(t)
  end
end
