platform :ios, '15.0'

flutter_sdk_root = ENV['FLUTTER_ROOT'] or
  raise 'FLUTTER_ROOT env-var is not set; run `flutter` once or set it manually'

require File.join(flutter_sdk_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks!                       # or use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|    # or your loop + flutter_additional…
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Set all pods to use automatic provisioning profiles
      c.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'Automatic'
      c.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      # Remove any manual provisioning profile settings
      c.build_settings.delete('PROVISIONING_PROFILE')
      c.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      c.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'Automatic'
    end
    flutter_additional_ios_build_settings(t)
  end
end
