platform :ios, '16.0'

flutter_sdk_root = ENV['FLUTTER_ROOT'] or
  raise 'FLUTTER_ROOT env-var is not set; run `flutter` once or set it manually'

require File.join(flutter_sdk_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks!                       # or use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name == 'Pods-Runner'
      t.build_configurations.each do |c|
        if c.name == 'Release'
          c.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          c.build_settings['CODE_SIGN_STYLE'] = 'Manual'
        end
      end
    end
    t.build_configurations.each do |c|
      # Pods are not independently signed
      c.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      c.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      c.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      c.build_settings.delete('PROVISIONING_PROFILE')
    end
    flutter_additional_ios_build_settings(t)
  end
end
