# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci 

    # Set up API key for App Store Connect
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_PRIVATE_KEY"],
      is_key_content_base64: true
    )

    # development profile (same bundle ID)
    match(
      api_key: api_key,
      type:    "development",
      readonly: false 
    )

    # Code signing with match
    match(
      api_key: api_key,
      type: "appstore",
    )

    # Build with Flutter
    sh("cd .. && bundle exec flutter build ios --release --no-codesign")

    profile_specifier =
    lane_context[:MATCH_PROVISIONING_PROFILE_MAPPING][ENV['APP_IDENTIFIER']]
  
    # bump build number to current UTC timestamp YYYYMMDDHHMM
    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: Time.now.utc.strftime("%Y%m%d%H%M")
    )

    build_app(
      scheme:        "Runner",
      configuration: "Release",
      export_method: "app-store",
      destination:   "generic/platform=iOS",
      xcargs: %Q(CODE_SIGN_STYLE=Manual \
                CODE_SIGN_IDENTITY="Apple Distribution" \
                PROVISIONING_PROFILE_SPECIFIER="#{profile_specifier}")
    )

    upload_to_testflight(api_key: api_key)
  end
end
