name: DCM (Dart Code Metrics)

on:
  push:
    branches: ["main"]

jobs:
  dcm:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5

      - name: 🚀 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0"
          channel: "stable"

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔍 Flutter analyze
        run: flutter analyze

      - name: 📊 Install DCM
        run: |
          sudo apt-get update
          wget -qO- https://dcm.dev/pgp-key.public | sudo gpg --dearmor -o /usr/share/keyrings/dcm.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dcm.gpg arch=amd64] https://dcm.dev/debian stable main' | sudo tee /etc/apt/sources.list.d/dcm_stable.list
          sudo apt-get update
          sudo apt-get install -y dcm

      - name: 📊 Run DCM
        run: dcm analyze lib --ci-key="${{ secrets.DCM_CI_KEY }}" --email="${{ secrets.DCM_EMAIL }}"
