name: iOS Test Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Build iOS for simulator
      run: |
        flutter build ios --simulator --debug
      env:
        FLUTTER_BUILD_MODE: debug
    
    - name: Test iOS build
      run: |
        flutter test
